### ISSUE TITLE
Passing RSA encryption Padding Scheme to CmsEnvelopedDataGenerator

### ISSUE THREAD

**Issue by lorenzograssi** [bcgit/bc-csharp#106]
In the C# version of BC I cannot find a way to specify the algorithmId for the key encryption

It takes the algorithmId from SubjectPublicKeyInfo that comes from the PublicKey and has the base encryption algorithm (ie RSA 1.2.840.113549.1.1.1)
In this way it is not possible to specify a different padding  (ie OAEP 1.2.840.113549.1.1.7)

**Java**
_encrypter.addRecipientInfoGenerator(new JceKeyTransRecipientInfoGenerator(publicCert, oaepAlgId).setProvider("BC"));_

**C#**
_KeyTransRecipientInfoGenerator ktrig = new KeyTransRecipientInfoGenerator();
ktrig.RecipientCert = cert;
recipientInfoGenerators.Add(ktrig);_

Is there an alternative way to specify padding scheme on CmsEnvelopedDataGenerator?

**Comment by jstedfast** [comment]
Most likely you can simply pass "1.2.840.113549.1.1.7" as the algorithm id.

**Comment by lorenzograssi** [comment]
Hi Jeffrey, ok but where?
I'm using the AddKeyTransRecipient method with certificate as param
public void AddKeyTransRecipient(X509Certificate cert)

I cannot find an overload that will accept the key encryption algoritm id

**Comment by jstedfast** [comment]
CmsEnvelopedDataGenerator.Generate() takes an algorithm identifier.

**Comment by lorenzograssi** [comment]
Yes, but this is the algorithm for content encryption (in my case AES128-CBC)
I need to set the algorithm for the key encryption (in my case RSASSA-OAEP)

**Comment by lorenzograssi** [comment]
I have added a new property to choose the content key encryption algorithm, since I have no permission to pull the request, I share the code here:

_CMSEnvelopedGenerator.cs_


```
	/**
	 * add a recipient.
	 *
	 * @param cert recipient's public key certificate
	 * @exception ArgumentException if there is a problem with the certificate
	 */
	public void AddKeyTransRecipient(
			X509Certificate cert)
	{
            AddKeyTransRecipient(cert, null);
	}

        /**
         * add a recipient.
         *
         * @param cert recipient's public key certificate
         * @param keyEncryptionAlgorithmID AlgorithmID for key encryption
         * @exception ArgumentException if there is a problem with the certificate
         */
        public void AddKeyTransRecipient(
            X509Certificate cert, AlgorithmIdentifier keyEncryptionAlgorithmID)
        {
            KeyTransRecipientInfoGenerator ktrig = new KeyTransRecipientInfoGenerator();
            ktrig.RecipientCert = cert;
            ktrig.AlgorithmId = keyEncryptionAlgorithmID;

            recipientInfoGenerators.Add(ktrig);
        }
```


_KeyTransRecipientInfoGenerator.cs_

```
        private AlgorithmIdentifier keyEncryptionAlgorithm;

        internal AlgorithmIdentifier AlgorithmId
        {
            set
            {
                this.keyEncryptionAlgorithm = value;
            }
        }

	public RecipientInfo Generate(KeyParameter contentEncryptionKey, SecureRandom random)
	{
		byte[] keyBytes = contentEncryptionKey.GetKey();
                if (keyEncryptionAlgorithm == null)
                     keyEncryptionAlgorithm = info.AlgorithmID;

                IWrapper keyWrapper = Helper.CreateWrapper(keyEncryptionAlgorithm.Algorithm.Id);
		keyWrapper.Init(true, new ParametersWithRandom(recipientPublicKey, random));
		byte[] encryptedKeyBytes = keyWrapper.Wrap(keyBytes, 0, keyBytes.Length);
              .....

```

**Comment by owlstead** [comment]
It seems that this was closed after posting the source code, but that doesn't mean it is integrated and solved for the library, it seems to me.
