### ISSUE TITLE
Antivirus detection message

### ISSUE THREAD

**Issue by Mathavana** [bcgit/bc-csharp#115]
Hi,
I am using BouncyCastle.Crypto.dll for encryption. After I deployed my application to production server, encounter an Antivirus detection message. 
Risk: SONAR.Heuristic.159
![image](https://user-images.githubusercontent.com/5356325/38409774-49318fb8-39b5-11e8-81ed-3b24d72fcc96.png)

Please help me, Is it fine to use this dll?

**Comment by peterdettman** [comment]
What does the DLL have to do with ot.exe?

In any case, we've never had a report that the original DLL triggers an antivirus detection before. You should confirm that you have an unmodified version of our software by downloading from http://www.bouncycastle.org/csharp/index.html, where there is a sha256 checksum provided. Alternatively, you could build the DLL yourself from the provided source code.

**Comment by Mathavana** [comment]
ot.exe is my application. It use your dll for encryption/decryption. Downloaded the dll from the above mentioned URL.
