### ISSUE TITLE
Very Very Slow ToString In BigInteger

### ISSUE THREAD

**Issue by Xor-el** [bcgit/bc-csharp#119]
Hi,
for special cases, ToString (In Base 10) can take very very long to execute for BigIntegers where BitLength is >= 64
An Example Case is this
 BigInteger b = new BigInteger("2");
 BigInteger exp = b.Pow(65536);
 var  s = exp.ToString();

can anything be done to improve this, maybe a more optimal algorithm or implementation?

Regards.

**Comment by peterdettman** [comment]
Well, it could certainly be improved, but the functionality is mostly there for completeness.

The BigInteger class in BC exists primarily to support the cryptographic functions of the rest of the library and conversion to base 10 is not really useful for that apart from debugging or test vectors, and even then it's normal to use hexadecimal (i.e. ToString(16)). Also, efficiency is mostly concerned with bit lengths in the few-thousand range, and (in case you were expecting it), we don't attempt much in the way of clever handling for special values like powers-of-2.

**Comment by Xor-el** [comment]
@peterdettman , thanks for your explanation.

**Comment by peterdettman** [comment]
I found some time to improve this (changes take a while to mirror here). On my machine, ToString(10) for random 100,000 bit numbers now takes < 1 second.  Still not ideal, but a lot better.

**Comment by Xor-el** [comment]
@peterdettman , seems you forgot to make the push?

**Comment by Xor-el** [comment]
@peterdettman , have been finally able to test it, huge improvement noticed.
Thanks a lot. 
you can now close this issue if you please.
Thanks a bunch.
I own you one.

**Comment by peterdettman** [comment]
Glad it helped.
