### ISSUE TITLE
ECIES Encryption and Decryption With Public and Private Key Using AES 256 CBC PKCS7PADDING

### ISSUE THREAD

**Issue by Xor-el** [bcgit/bc-csharp#124]
@peterdettman, Ok, I wanted to implement ECIES Encryption and Decryption using BouncyCastle CSharp, since I could not find any CSharp examples for encrypting a message, I decided to adapt the java example I found [here](http://bouncy-castle.1462172.n4.nabble.com/ECC-with-ECIES-Encrypt-Decrypt-Questions-td4656750.html) to CSharp.
I started by replacing IESCipher with BufferedIesCipher and IESParameterSpec  with IesWithCipherParameters and I hit a bummer, BufferedIesCipher .Init threw a Platform.CreateNotImplementedException("IES");
Does anyone have any examples in CSharp I could use for implementing this?
Thanks.

**Comment by Xor-el** [comment]
later implemented this following samples from the Java code.

**Comment by lyesuk** [comment]
@Xor-el, Where can I refer your big creation.
 - These day, I also need C# ECIES library that is compatible with Java BC library.

**Comment by lyesuk** [comment]
> later implemented this following samples from the Java code.
Could I get the information what you did??

**Comment by Mofl2328** [comment]
For anyone else who runs into this here: If you need ECIES AES CBC with IV take a look at https://github.com/Sphere10/NPascalCoin/tree/master/src/NPascalCoin/Crypto They implemented the missing classes from the java bc so it works together with the IESwithAESCBC class from java.

Without IV might work it but at least with an initial vector there is no support from the csharp bc atm.
