### ISSUE TITLE
Confusion on the size of the counter, please help...

### ISSUE THREAD

**Issue by junjiequ** [bcgit/bc-csharp#127]
In SicBlockCipher.cs, i notice there's a line stating the maxCounterSizer is the min value between 8 and blockSize/2:

https://github.com/bcgit/bc-csharp/blob/b19e68a517e56ef08cd2e50df4dcb8a96ddbe507/crypto/src/crypto/modes/SicBlockCipher.cs#L60

While in the constructor: it states, counter = new byte[blockSize]...
https://github.com/bcgit/bc-csharp/blob/022e86493b52c8c8dfe414940acc3a04cdfa3382/crypto/src/crypto/modes/SicBlockCipher.cs#L32

I am really confused here... are they not conflicting with each other???

Could someone who knows the reason explain a bit please?

Thanks,
Junjie

**Comment by peterdettman** [comment]
Think of 'counter' as the counter block (so it's size is exactly 1 block), made up of the nonce (or IV) plus an actual counter value. 'maxCounterSize' limits how much of the counter block can actually be used as the counter (thus requiring a certain minimum size for the IV).
