### ISSUE TITLE
Support for ASLR and DEP

### ISSUE THREAD

**Issue by dskidmor** [bcgit/bc-csharp#128]
I am auditing DLL's we are using in a project and noticed the Bouncy Castle C# API (checked version 1.8.2) is not using ASLR or DEP. Using a tool like [PESecurity](https://github.com/NetSPI/PESecurity) I see:

    PS C:\Users\dskidmor\Downloads> Get-PESecurity -file .\BouncyCastle.Crypto.dll

    FileName         : C:\Users\dskidmor\Downloads\BouncyCastle.Crypto.dll
    ARCH             : I386
    ASLR             : False
    DEP              : False
    Authenticode     : False
    StrongNaming     : True
    SafeSEH          : N/A
    ControlFlowGuard : False
    HighentropyVA    : False

However, I tried out building the project myself using Visual Studio 2017 and my copy does support ASLR and DEP:

    PS C:\Users\dskidmor> Get-PESecurity -file bc-csharp\crypto\bin\Debug\lib\net20\BouncyCastle.dll

    FileName         : C:\Users\dskidmor\bc-csharp\crypto\bin\Debug\lib\net20\BouncyCastle.dll
    ARCH             : I386
    ASLR             : True
    DEP              : True
    Authenticode     : False
    StrongNaming     : True
    SafeSEH          : N/A
    ControlFlowGuard : False
    HighentropyVA    : False

I don't know much about the build infrastructure of the project, but are releases built with an older toolchain or with these features disabled? Would it be possible to turn on these security features in a future release?

**Comment by peterdettman** [comment]
Releases up to 1.8.2 were built with an old toolchain, yes. Future official releases will be switching to modern tools (see https://github.com/bcgit/bc-csharp/pull/68), and should have these enabled.
