### ISSUE TITLE
Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.1.0

### ISSUE THREAD

**Issue by jmawebtech** [bcgit/bc-csharp#129]
Hi,

I am trying to integrate this assembly into my app. It uses .NET 4.61 and MVC 5. On a standalone console app, it is fine. In my project, I get these errors.

1.8.1.0 has been referenced and it exists in by bin folder.

{"Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null"}

=== Pre-bind state information ===
LOG: DisplayName = BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Users/example/Source/Workspaces/example/Test/example.ConsoleClient/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Walmart.Sdk.Base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\example\Source\Workspaces\example\Test\example.ConsoleClient\bin\Debug\example.ConsoleClient.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/example/Source/Workspaces/example/Test/example.ConsoleClient/bin/Debug/BouncyCastle.Crypto.DLL.
WRN: Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by onovotny** [comment]
It looks like something is referencing an older version of BC before they checked in the strong name key. BC is strong named and the `PublicKeyToken` should not be null. 

Where are you getting BC from?

**Comment by jmawebtech** [comment]
The project was using 1.83 because it was .NET Core. I referenced the wrong version. I needed the .NET 4 version.
