### ISSUE TITLE
ECDsaSigner issue

### ISSUE THREAD

**Issue by dmac-coding** [bcgit/bc-csharp#131]
Hello,

It seems to me that there are two equivalent ways construct an ECSDSA verifier.
`ISigner verifier2 = SignerUtilities.GetSigner("SHA-256withECDSA")`
and
`ECDsaSigner ecDSAVerifier = new ECDsaSigner();`

I'm attaching a test case where I use both methods to verify the same data with the same key and the same signature, but the ISigner method works while the ECDsaSigner method does not. 

Thanks!
 
[BugReport.cs.txt](https://github.com/bcgit/bc-csharp/files/2124483/BugReport.cs.txt)

**Comment by Xor-el** [comment]
@dmac-coding, they are not equivalent, one hash the message before signing/verifying, the other doesn't.

**Comment by dmac-coding** [comment]
Ah. Thanks, that explains it.
