### ISSUE TITLE
Any way to specify custom CTR counter in BouncyCastle AES cipher?

### ISSUE THREAD

**Issue by Xor-el** [bcgit/bc-csharp#132]
I am using BouncyCastle's c# library to perform some file encryption/decryption with it's AES cipher in CTR mode (no padding).

In order to be able to decrypt portions of a file without needing the others, I need to increment the counter value manually without toying with the IV. I cannot find a way to do this. Am I missing something?

**Comment by cipherboy** [comment]
@Xor-el CTR mode works by taking the IV as the counter value 0, and incrementing the IV as if it were an unsigned 128-bit integer. To decrypt an inner block, you'd manually do that addition and start on that desired block. As far as I can tell, bc-csharp doesn't assert the trailing bits are zero so you should be good.
