### ISSUE TITLE
Expired Patent of IDEA engine

### ISSUE THREAD

**Issue by bjoernbusch** [bcgit/bc-csharp#134]
The following [file](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/engines/IdeaEngine.cs) has a remark to royalties in case of commercial use.

In the [Java](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/engines/IDEAEngine.java) version, this remark has been changed that the patent expired. Should this also be reflected in the C# version?

**Comment by peterdettman** [comment]
Thanks for pointing that out, I've updated the IdeaEngine.cs comments to match the java version.

**Comment by bjoernbusch** [comment]
Thanks for following up so quickly. When will you merge these changes?
