### ISSUE TITLE
add support for Curve448

### ISSUE THREAD

**Issue by chrishaly** [bcgit/bc-csharp#135]
I found class about 448 such as Ed448, Nat448, X448, X448Field but Curve448. Are there plan to add Curve448?

**Comment by peterdettman** [comment]
Between X448 (from RFC 7748) and Ed448 (RFC 8032), what you are looking for should already be there. If that's not the case, I'd need more details of what you are trying to do, or what software you are trying to interoperate with.

Please understand that X448/Ed448 are currently very low-level implementations - usable, just not yet available in the org.bouncycastle.crypto.** classes like other algorithms.

**Comment by chrishaly** [comment]
For example I can use Curve255 to generate KeyPair, and use KeyPairs to calcuate shared key.

Code as following:
```csharp
const string curveName = "curve25519";
var curve = CustomNamedCurves.GetByName(curveName);
var ecSpec = new ECDomainParameters(curve.Curve, curve.G, curve.N, curve.H, curve.GetSeed());
var secureRandom = new SecureRandom();
var keyGenParam = new ECKeyGenerationParameters(ecSpec, secureRandom);
var gen = new ECKeyPairGenerator();
gen.Init(keyGenParam);

var aliceKey = gen.GenerateKeyPair();
var bobKey = gen.GenerateKeyPair();

var ecdh = new ECDHBasicAgreement();
ecdh.Init(aliceKey.Private);
var shareKey = ecdh.CalculateAgreement(bobKey.Public);
var shareKeyBytes = shareKey.ToByteArray();
```

In this case I want to use curve448 instead of curve25519.

**Comment by peterdettman** [comment]
Oh, I see. That implementation of curve25519 is actually in Short Weierstrass form and not the more natural form that you might be expecting (from RFC 7748 and elsewhere). It was provided as an interim solution until we could introduce "proper" Montgomery and/or Edwards based implementations. It will probably be deprecated in due course. I don't see much value in providing an equivalent curve448 in that vein.

The new Org.BouncyCastle.Math.EC.Rfc7748 (and Rfc8032) classes are "proper" implementations and usable now, though we still need to integrate them into higher-level APIs.

**Comment by chrishaly** [comment]
Thanks for your replies.

Till now curve25519 is safe but may not after many years, so I'm looking for more safe curve solution.

Why I asked for curve448 is: Signal Message X3DH Key Agreement Protocol recommond X448 (https://signal.org/docs/specifications/x3dh/), and all index of X448 is green in https://safecurves.cr.yp.to/ (locate to table below words "security requirements beyond ECDLP security").

It's hardly for me to use low-level APIs. As you said need to integrate them into higher-level APIs, so is there a plan and when will the high-level APIs be ready?

**Comment by peterdettman** [comment]
All the higher-level classes for agreement and signing have now been added and will be in 1.8.4.

**Comment by chrishaly** [comment]
> All the higher-level classes for agreement and signing have now been added and will be in 1.8.4.

I've found Ed448KeyPairGenerator thanks
