### ISSUE TITLE
IX509Store.GetMatches Unsorted IssuerDN returns empty collection.

### ISSUE THREAD

**Issue by Jeroen-Van-Loocke** [bcgit/bc-csharp#136]
I'm experiencing the following issue: 
I want to get the certificate that matches the signer and do this with the code below.
```
var scms = new CmsSignedData(tvi.Value).SignedData;
scms.GetSignerInfos().GetSigners().OfType<SignerInformation>().FirstOrDefault();
var certStore = scms.GetCertificates("Collection");
var cert = certStore.GetMatches(signer.SignerID).OfType<X509Certificate>().FirstOrDefault();
```
This works in most cases but sometimes the "signer.SignerID" contains an IssuerDN that is not sorted the same as in the certificate. Therefore the GetMatches returns empty because of the following check that happens in the "Match" method of the X509CertStoreSelector `public virtual bool Match(object obj)`.

```
if (this.issuer != null && !this.issuer.Equivalent(x509Certificate.IssuerDN, true))
{
	return false;
}
```

`public bool Equivalent(X509Name other, bool inOrder)`

This Calls the "Equivalent" method of the X509Name class. The issue is that here "TRUE" is given as a fixed value. But because there is a possibility that this is not both in the same order it fails and returns false. This escalates to an empty collection in the "GetMatches" method.

Is there a possibility that the value of the inOrder parameter can be past through the methods so the user can determine if it needs to be ordered correctly or not?

Thanks in advance.
Jeroen Van Loocke

**Comment by peterdettman** [comment]
I've added 'bool IgnoreX509NameOrdering' property to X509CertStoreSelector (which signer.SignerID is an instance of). Setting that to true will toggle the 'inOrder' value passed through to Equivalent(...) when matching. Changes will appear in a few days as part of 1.8.3.

**Comment by Jeroen-Van-Loocke** [comment]
Thank you for making this change.
