### ISSUE TITLE
PollRepContent - Missing Constructor

### ISSUE THREAD

**Issue by agpreynolds** [bcgit/bc-csharp#137]
The PollRepContent class in Org.BouncyCastle.Asn1.Cmp is missing constructors which are provided in the java equivalent API.
https://github.com/bcgit/bc-java/blob/5fdb1face92f596300323c25cba9fe18726645e8/core/src/main/java/org/bouncycastle/asn1/cmp/PollRepContent.java

The following constructors should be implemented:
`public PollRepContent(
DerInteger certReqId,
DerInteger checkAfter)`

`public PollRepContent(
DerInteger certReqId,
DerInteger checkAfter,
PKIFreeText reason)`

**Comment by peterdettman** [comment]
#138 merged.
