### ISSUE TITLE
Relax constraint on length only constructors for Blake2b/Blake2s

### ISSUE THREAD

**Issue by tabrath** [bcgit/bc-csharp#142]
The constructors of Blake2b and Blake2s doesn't follow the specification as it's too restrictive of digest bit lengths. This is fixed in the java implementation (https://github.com/bcgit/bc-java/commit/2d6ae35ef80f11fcc1b40671a32205a63648a8b8), see https://github.com/bcgit/bc-java/issues/352 for context.

I'd make a PR if you want help with that.

**Comment by peterdettman** [comment]
The java changes have now been ported over to C# (changes may take some time to mirror here). Thanks again for the report.
