### ISSUE TITLE
this java code how to use C# to replease...main "BC"

### ISSUE THREAD

**Issue by supperlitt** [bcgit/bc-csharp#146]
`KeyFactory.getInstance("RSA", "BC").generatePrivate(new PKCS8EncodedKeySpec(data))`

use C#

`AsymmetricKeyParameter asymmetricKeyParameter = PrivateKeyFactory.CreateKey(keyBytes);`

the C# will break an error..
if java not used "BC", it will alike break error...but android 7.1 + .,.the alike not error

how tu do with C# not error....

翻译：
以上代码。java如果加入了“BC"就不会报错。但是C#没有这方面的处理。我当前版本是 4.0的
应该如何处理才不会报错呢？

**Comment by peterdettman** [comment]
`PrivateKeyFactory.CreateKey` is the correct approach. It's not possible to say why it doesn't work for this particular key without more information. However this sort of question belongs on the mailing list.
