### ISSUE TITLE
crypto.dotnet, crypto.pcl, and crypto.pcl2 do not compile

### ISSUE THREAD

**Issue by tschmit** [bcgit/bc-csharp#150]
It seems to have 15 errors, all the same in an related to `MethodImplOptions`

Gravity	Code	Description	Projet	File	Line	Suppression State
Error	CS0117	'MethodImplOptions' ne contient pas de définition pour 'Synchronized'	crypto.dotnet, crypto.pcl, crypto.pcl2	D:\dev\fromGit\bc-csharp\crypto\src\math\ec\rfc7748\X448.cs	64	Actif

**Comment by peterdettman** [comment]
We've now replaced all those usages with `lock` blocks. Thanks for the report.
