### ISSUE TITLE
compilation error BouncyCastle-PCL

### ISSUE THREAD

**Issue by tschmit** [bcgit/bc-csharp#154]
Error CS1061
'AutoResetEvent' no definition for 'Close' and no accessible extension method for 'Close' with a first argument of type 'AutoResetEvent' can be found (une directive using ou une référence d'assembly est-elle manquante ?)
crypto.dotnet, crypto.pcl, crypto.pcl2
D:\dev\fromGit\bc-csharp\crypto\src\crypto\prng\ThreadedSeedGenerator.cs	116

May be: `autoResetEvent.Dispose();`

**Comment by peterdettman** [comment]
Fixed.
