### ISSUE TITLE
CMS version 2.2 with SHA256WithRSAEncryption algorithm

### ISSUE THREAD

**Issue by jeisonperes** [bcgit/bc-csharp#170]
Hello,
I need to sign a json document with these requirements: CMS version 2.2, with SHA256WithRSAEncryption algorithm, but I did not find property to set the in c# signer.setSignaturePolicy(new ADRBCMS_2_2()) in class CmsSigner  . This property exists?
This guy have the same problem. (https://stackoverflow.com/questions/53485946/cms-version-2-2-sha256withrsaencryption?newreg=3fdc12c1eaf84a439aa1a71f70f41808)

Thank you

**Comment by dghgit** [comment]
I'd recommend asking whoever wrote the API. It's not one of ours.
