### ISSUE TITLE
No Key Length Check Performed In BlowFishEngine

### ISSUE THREAD

**Issue by Xor-el** [bcgit/bc-csharp#172]
The BlowFish Standard defines that the Key used for the BlowFish operation must be of Length **0 .. 448 bits** and be a Multiple of 8. Unfortunately I cannot see any check performed to that effect in [BlowFishEngine.cs](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/engines/BlowfishEngine.cs#L422).
A similar check was performed in [AESEngine.cs](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/engines/AesEngine.cs#L295) and I recommend something similar be replicated in the BlowFishEngine case.

**Comment by dghgit** [comment]
Thanks for the report. A range check has been added.
