### ISSUE TITLE
How to implement CMP enrollment message for an RA, using BouncyCastle

### ISSUE THREAD

**Issue by Mathavana** [bcgit/bc-csharp#173]
I am trying to implement CMP client using C#
CMP using RA mode, how to send the POST request to create the user and certificate in EJBCA

Followed this example: http://blog.ejbca.org/2014/03/using-cmp-with-bouncycastle-java-api.html

**Comment by bcgit** [comment]
Funnily we're actually doing some work on CMP and C# at the moment. Will update this issue as things start to take shape.

**Comment by Mathavana** [comment]
Please look at the gist, I tried to create CMP using C#.
https://gist.github.com/Mathavana/730c1d98827728d04b99262b357d0ff7

Referred from EJBCA CMPTestCase.
https://github.com/rgorosito/ejbca/blob/master/modules/systemtests/src-test/org/ejbca/core/protocol/cmp/CmpTestCase.java

**Comment by bcgit** [comment]
basic support for CMP/CRMF has now been added.
