### ISSUE TITLE
Discrepancy between signature algorithm identifiers

### ISSUE THREAD

**Issue by fedelippo** [bcgit/bc-csharp#183]
Hi, I'm hitting a blocking issue. I'm in the process to write a CMP Certificate Confirmation Content and the code blows up while trying to create the _CertHash_. After investigation it turns out that the problem is caused by the value (_"SHA-256withRSA_") in the _sigAlgName_ field of the certificate which is worked out using this code ([X509Certificate.cs:247](https://github.com/onovotny/bc-csharp/blob/b4b7663fae395ccf1efa9a2e0817e00bcf015775/crypto/src/x509/X509Certificate.cs#L247))
`public virtual string SigAlgName
		{
            get { return SignerUtilities.GetEncodingName(c.SignatureAlgorithm.Algorithm); }
		}` 

[SignerUtilities.cs:67](https://github.com/onovotny/bc-csharp/blob/b4b7663fae395ccf1efa9a2e0817e00bcf015775/crypto/src/security/SignerUtilities.cs#L67) associates a specific PkcsObjectIdentifier to a string (the algorithm's name), e.g. 
`algorithms[PkcsObjectIdentifiers.Sha256WithRsaEncryption.Id] = "SHA-256withRSA";`

Now, when the [CMSSignedGenerator:346](https://github.com/onovotny/bc-csharp/blob/b4b7663fae395ccf1efa9a2e0817e00bcf015775/crypto/src/cms/CMSSignedGenerator.cs#L346) looks this name up in its algorithms list it doesn't find it, and the reason is that the [CMSSignedGenerator.cs:60](https://github.com/onovotny/bc-csharp/blob/b4b7663fae395ccf1efa9a2e0817e00bcf015775/crypto/src/cms/CMSSignedGenerator.cs#L60) associates a different algorithm's name to the same PkcsObjectIdentifier: e.g.
`algorithms["SHA256WITHRSA"] = PkcsObjectIdentifiers.Sha256WithRsaEncryption;`

The problem is clearly that the same identifier `PkcsObjectIdentifiers.Sha256WithRsaEncryption` is transcoded in 2 different names across the codebase.

Adding `algorithms["SHA-256WITHRSA"] = PkcsObjectIdentifiers.Sha256WithRsaEncryption;
` to CMSSignedGenerator addresses the issue.

Obviously this should be done for every digest algorithm present in the SignerUtilities.cs. 

I look forward to hearing from you.
Thanks and regards,
Filippo Biondi

**Comment by dghgit** [comment]
Closing as the PR for this has been merged.
