### ISSUE TITLE
X509V2CrlGenerator.Generate using Smart card or Luna HSM stored private key

### ISSUE THREAD

**Issue by vazmuten** [bcgit/bc-csharp#187]
Hi!
I have created a CRL using X509V2CrlGenerator class but I could not pass Smart card/Luna HSM stored private key to the Generate method in order to generate/sign the CRL. Does any of you know how to do it or the Generate method does not support it at all.

**Comment by agpreynolds** [comment]
Hi @vazmuten I have had this exact problem working with a Luna HSM so i'm hopeful I can help out here.

First of all the Luna HSM does not allow you to extract a private key in plaintext. You can only extract the key if you wrap (encrypt) it using a symmetric key. In order to use BouncyCastle's built in Asn1SignatureFactory you would need to find a way to somehow decrypt the exported key, probably by hard-coding the symmetric wrapping key within your application code.

However, the above approach makes a mockery of the Luna's security policy and I would highly discourage it.

The approach I took was to create my own implementation of ISignatureFactory which actually performs the signing on the HSM using Pkcs11 API's.

This issue show's some of the thought processes that went into designing the solution, however following the changes I was able to produce a slightly more elegant solution. https://github.com/bcgit/bc-csharp/issues/153

If you need some help with using the PKCS11 API's I can provide you some more information tomorrow about specific mechanism's I used when I have access to my work PC.

**Comment by vazmuten** [comment]
The smart card/HSM private keys should not leave the secure environment for obvious reasons.  I will appreciate any help concerning the implementation of ISignatureFactory to be used for signing with these keys especially with the Luna.

**Comment by agpreynolds** [comment]
So I was able to create the ISignatureFactory with a minimal implementation of two classes, the ISignatureFactory and ISigner. See below.

```
public class CustomSignatureFactory : ISignatureFactory
    {
        private readonly int _keyHandle;

        public CustomSignatureFactory(int keyHandle)
        {
            this._keyHandle = keyHandle;
        }

        public IStreamCalculator CreateCalculator()
        {
            var sig = new CustomDigestSigner(this._keyHandle);

            sig.Init(true, null);

            return new DefaultSignatureCalculator(sig);
        }

        // TODO Only supporting SHA256?
        public object AlgorithmDetails => new AlgorithmIdentifier(PkcsObjectIdentifiers.Sha256WithRsaEncryption);
    }
```
```
    internal class CustomRsaDigestSigner : ISigner
    {
        private readonly int _keyHandle;
        private byte[] _input;

        public CustomRsaDigestSigner(int keyHandle)
        {
            this._keyHandle = keyHandle;
        }

        public void Init(bool forSigning, ICipherParameters parameters)
        {
            this.Reset();
        }

        public void Update(byte input)
        {
            throw new NotImplementedException();
        }

        public void BlockUpdate(byte[] input, int inOff, int length)
        {
            this._input = input.Skip(inOff).Take(length).ToArray();
        }

        public byte[] GenerateSignature()
        {
            // This method doesn't exist, you will need to implement your own method here
            return this.DoSignature(this._input, this._keyHandle);
        }

        public bool VerifySignature(byte[] signature)
        {
            throw new NotImplementedException();
        }

        public void Reset() {}

        public string AlgorithmName => "SHA-256withRSA";
    }
```

Hope you find this helpful.

**Comment by vazmuten** [comment]
THANK YOU! This is all I needed and already successfully implemented the smart card CRL sign using this code. In next days LUNA signing will be also done :)

**Comment by vazmuten** [comment]
> So I was able to create the ISignatureFactory with a minimal implementation of two classes, the ISignatureFactory and ISigner. See below.
> 
> ```
> public class CustomSignatureFactory : ISignatureFactory
>     {
>         private readonly int _keyHandle;
> 
>         public CustomSignatureFactory(int keyHandle)
>         {
>             this._keyHandle = keyHandle;
>         }
> 
>         public IStreamCalculator CreateCalculator()
>         {
>             var sig = new CustomDigestSigner(this._keyHandle);
> 
>             sig.Init(true, null);
> 
>             return new DefaultSignatureCalculator(sig);
>         }
> 
>         // TODO Only supporting SHA256?
>         public object AlgorithmDetails => new AlgorithmIdentifier(PkcsObjectIdentifiers.Sha256WithRsaEncryption);
>     }
> ```
> ```
>     internal class CustomRsaDigestSigner : ISigner
>     {
>         private readonly int _keyHandle;
>         private byte[] _input;
> 
>         public CustomRsaDigestSigner(int keyHandle)
>         {
>             this._keyHandle = keyHandle;
>         }
> 
>         public void Init(bool forSigning, ICipherParameters parameters)
>         {
>             this.Reset();
>         }
> 
>         public void Update(byte input)
>         {
>             throw new NotImplementedException();
>         }
> 
>         public void BlockUpdate(byte[] input, int inOff, int length)
>         {
>             this._input = input.Skip(inOff).Take(length).ToArray();
>         }
> 
>         public byte[] GenerateSignature()
>         {
>             // This method doesn't exist, you will need to implement your own method here
>             return this.DoSignature(this._input, this._keyHandle);
>         }
> 
>         public bool VerifySignature(byte[] signature)
>         {
>             throw new NotImplementedException();
>         }
> 
>         public void Reset() {}
> 
>         public string AlgorithmName => "SHA-256withRSA";
>     }
> ```
> Hope you find this helpful.

**Comment by mnns** [comment]
I'm using this ISignatureFactory code with Azure KeyVault (HSM saas).
Getting "invalid signature" - don't know what to do, can't find any documentation and no one can help.

This is my code:

```
 public byte[] GenerateSignature()
            {
                // This method doesn't exist, you will need to implement your own method here
                //return this.DoSignature(this._input, this._keyHandle);

                //Crypto Client (Specific Key)
                try
                {

                    //Crypto Client (Specific Key)
                    CryptographyClient identitiesCAKey_cryptoClient = new CryptographyClient(
                        keyId: new Uri("https://xxx.vault.azure.net/keys/identities-new-ec/xxxxx"),
                        credential: new ClientSecretCredential(

                              tenantId: "xxx", //Active Directory: ""
                              clientId: "xxx", //Application id?
                              clientSecret: "xxxx"
                              )
                    );
                    //byte[] reversedBytes = this._input;
                    //Array.Reverse(reversedBytes);
                    //SignResult signResult = identitiesCAKey_cryptoClient.SignData(Azure.Security.KeyVault.Keys.Cryptography.SignatureAlgorithm.ES256, this._input);

                    //Array.Reverse(this._input);
                    var hasher = new SHA256CryptoServiceProvider();
                    var digest = hasher.ComputeHash(this._input);

                    SignResult signResult = identitiesCAKey_cryptoClient.Sign(Azure.Security.KeyVault.Keys.Cryptography.SignatureAlgorithm.ES256, digest);
                    return signResult.Signature;

                }
                catch (Exception ex)
                {

                    throw ex;
                }

                return null;
            }
```

Thanks!

**Comment by agpreynolds** [comment]
With limited knowlege of the Azure KeyVault I can only guess at what might be wrong... however, my guess would be that you might actually be hashing the input twice and using the bouncycastle hasher is not required.

You appear to be passing in the signature  method `SignatureAlgorithm.ES256` which implies to me that the hashing would actually be performed on the HSM.

Additionally the ES256 algorithm is based upon Eliptic Curve rather than RSA, has the rest of your custom signature factory been updated to reflect this?

Hope this helps, I appreciate from experience that these kind of HSM based issues can be extremely hard to find assistance with!

**Comment by mnns** [comment]
> With limited knowlege of the Azure KeyVault I can only guess at what might be wrong... however, my guess would be that you might actually be hashing the input twice and using the bouncycastle hasher is not required.
> 
> You appear to be passing in the signature method `SignatureAlgorithm.ES256` which implies to me that the hashing would actually be performed on the HSM.
> 
> Additionally the ES256 algorithm is based upon Eliptic Curve rather than RSA, has the rest of your custom signature factory been updated to reflect this?
> 
> Hope this helps, I appreciate from experience that these kind of HSM based issues can be extremely hard to find assistance with!

Thanks man. The "this._input" byte[] is actually around 500 bytes, so it's probably not hashed. It's the certificate data...

I did try to pass it to SignData() (not limitation on data size) and hash it locally (SHA256 -> 32 bytes) and pass it to Sign() which is used for signing digests and limits input to 32 bytes. 

So I guess this path is not what's causing the problem.

Thanks anyway!
