### ISSUE TITLE
there is no KDFCounterBytesGenerator in org.bouncycastle.crypto.generators

### ISSUE THREAD

**Issue by yp25** [bcgit/bc-csharp#189]
Hi, I previously use Java BouncyCastle library. Now I  need to use C#, I found that there is no class for KDFCounterBytesGenerator  in here  [https://github.com/bcgit/bc-csharp/tree/master/crypto/src/crypto/generators](url) . In Java there is a class KDFCounterBytesGenerator  [https://github.com/bcgit/bc-java/tree/master/core/src/main/java/org/bouncycastle/crypto/generators](url)

Any plan to add KDFCounterBytesGenerator .cs ? Thank you

**Comment by mwcw** [comment]
Hi,

This has now been implemented.

MW

**Comment by yp25** [comment]
hi MW,  
thank you very much

**Comment by mwcw** [comment]
No worries!
