### ISSUE TITLE
DotNetUtilities.ToRSA Creating temp files at AppData\Roaming\Microsoft\Crypto\RSA

### ISSUE THREAD

**Issue by ShuchinIL** [bcgit/bc-csharp#191]
I am using Bouncy Caste DotNetUtilities.ToRSA(RsaKeyParameters rsaKey) to create RSA object and encrypt the data with pkcs1 padding.

Every time when I do encryption a temp file is getting created at the server location.

Here is my code snippet,

` public static string BouncyRsaEncrypt(string data, string clientPublicKey) 
{
         string encryptedString;
         if (string.IsNullOrEmpty(clientPublicKey)) 
        {
                 throw new Exception("Client Public Key is empty");
         }
         byte[] publicKeyBytes = Convert.FromBase64String(clientPublicKey);
         Asn1Encodable asn1Encodable;
         using(var stream = new MemoryStream(publicKeyBytes)) 
         {
                 asn1Encodable = Asn1Object.FromStream(stream);
         }
        
              AlgorithmIdentifier algorithmIdentifier = new AlgorithmIdentifier(PkcsObjectIdentifiers.IdRsaesOaep);
         using(algorithmIdentifier as IDisposable) 
            {

                 RsaKeyParameters rsaKeyParameters = (RsaKeyParameters) PublicKeyFactory.CreateKey(new SubjectPublicKeyInfo(algorithmIdentifier, asn1Encodable));
                 using(rsaKeyParameters as IDisposable) {
                         var rsa = DotNetUtilities.ToRSA(rsaKeyParameters);
                         byte[] encbyte = rsa.Encrypt(Encoding.UTF8.GetBytes(data), RSAEncryptionPadding.Pkcs1);
                         encryptedString = Convert.ToBase64String(encbyte);
                         rsa.Clear();
                         rsa.Dispose();
                 }
         }

         return encryptedString;
 }`

**Comment by digitalpowers** [comment]
I am having a similar problem when calling 
 DotNetUtilities.ToRSA(rsaKeyParameters);
It appears to be the line 
RSACryptoServiceProvider rsaCsp = new RSACryptoServiceProvider(csp);
that creates the temporary file.  I found that after calling ToRsa if i cast the returned RSA object as an RSACryptoServiceProvider  and tell it not to *PersisteKeyInCsp* then it will remove the file on dispose of the private key.

```
                var rsa =  DotNetUtilities.ToRSA(rsaKeyParameters);
                if (rsa is RSACryptoServiceProvider rsaCsp)
                {
                    rsaCsp.PersistKeyInCsp = false;
                }
```

**Comment by ShuchinIL** [comment]
CspParameters csp = new CspParameters();
            csp.KeyContainerName = string.Format("BouncyCastle-{0}", Guid.NewGuid());
            csp.Flags = CspProviderFlags.CreateEphemeralKey;
            RSACryptoServiceProvider rsaCsp = new RSACryptoServiceProvider(csp);
            //rsaCsp.PersistKeyInCsp = false;
            rsaCsp.ImportParameters(rp);

--I am using this way
