### ISSUE TITLE
PgpLiteralData input stream support UTF7 not UTF8 

### ISSUE THREAD

**Issue by nsabiyera** [bcgit/bc-csharp#193]
The code below seems to be working fine when I use UTF7 encoding but not when I am using UTF8. The output has some unprintable characters

                          `PgpLiteralData literalData = (PgpLiteralData)pgpCompressedFactory.NextPgpObject();
                                using (Stream stream = literalData.GetInputStream())
                                {                               
                                    
                                    byte[] bytes = IOHelper.ReadStream(stream);

                                    byte[] byte_utf8 = Encoding.Convert(Encoding.UTF7, Encoding.UTF8, bytes);
                                    string output1 = System.Text.Encoding.UTF7.GetString(bytes);

                                    string output2 = System.Text.Encoding.UTF8.GetString(bytes);

                                    output = new UTF8Encoding(true).GetString(byte_utf8);
                                }`

**output1** utf-7 Ûâê
**output2** utf-8 ���
**output** utf-8(after bytes have been converted) Ûâê

Is the encoding format controlled in the library or is in PGP message that I am reading?

**Comment by jstedfast** [comment]
What you've discovered is that the data encoded in the PGP packet was encoded in UTF-7 and not UTF-8.

If the raw data is in UTF-7, you cannot use UTF-8 to convert it into a string.

**Comment by nsabiyera** [comment]
Thanks for the clarification, I have requested if that data can be encoded using UTF-8
