### ISSUE TITLE
Code changes break CF compatibility

### ISSUE THREAD

**Issue by oznetmaster** [bcgit/bc-csharp#20]
It seems as if .NET CF is being dropped?  Many of the newest code changes are not CF compatible, but they are not being conditioned by  CF.

For instance:

		private static long counter = Times.NanoTime ();

		private static long NextCounterValue ()
			{
			return Interlocked.Increment (ref counter);
			}

where Interlocked.Increment (Int64) is not supported in CF.

**Comment by peterdettman** [comment]
It's still intended to support CF, at least in the next release, so we'll get this fixed.

**Comment by peterdettman** [comment]
I've added .NET CF alternative code for the Interlocked.Increment calls. Note that (as I posted to the mailing list) I no longer have a build environment for .NET CF, so we cannot guarantee full .NET CF compatibility in the (imminent) 1.8 release unless someone in the community steps up to at least give us a list of issues.
