### ISSUE TITLE
Argon2 Support

### ISSUE THREAD

**Issue by sopelt** [bcgit/bc-csharp#202]
Hi, now that the Java Bouncy Castle has added support for Argon2 (which should be the go to password hashing algorithm for new systems according to best practices like https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Password_Storage_Cheat_Sheet.md#leverage-an-adaptive-one-way-function ) are there any plans (or interest) in adding it to bc-csharp as well?

Kind regards

**Comment by peterdettman** [comment]
Merged https://github.com/bcgit/bc-csharp/pull/520 which resolves this.
