### ISSUE TITLE
BouncyCastle 1.8.5 is not compatible with .Net Core 2.0

### ISSUE THREAD

**Issue by AmarJeetY** [bcgit/bc-csharp#204]
Whenever I try to compile my application which uses BC 1.8.5 I get warning that the package is not compatible to your project. Is there any plan to update the package in near future ?

**Comment by bdamm** [comment]
I'm interested in BC's .NET future as well.

**Comment by VahidN** [comment]
Try this one: https://www.nuget.org/packages/Portable.BouncyCastle/

**Comment by jstedfast** [comment]
As VahidN pointed out, you want to use @onovotny's fork. He's got an active PR to add support for .NET Core here: https://github.com/bcgit/bc-csharp/pull/68

**Comment by onovotny** [comment]
I just released 1.8.6 today.

**Comment by peterdettman** [comment]
https://www.nuget.org/packages/BouncyCastle.Cryptography is now available as the official NuGet.
