### ISSUE TITLE
 'pad block corrupted'' Exception in Rijndael Decryption

### ISSUE THREAD

**Issue by vasilijgla** [bcgit/bc-csharp#210]
I've described my situation [here](https://stackoverflow.com/questions/57306311/how-to-fix-org-bouncycastle-crypto-invalidciphertextexception-pad-block-corru)
losks like PaddedBufferedBlockCipher works not correct with  RijndaelEngine(256)

**Comment by peterdettman** [comment]
Answered at stackoverflow.
