### ISSUE TITLE
CMSEnvelopedData: Adding RSAES-OAEP as key encryption algorithm

### ISSUE THREAD

**Issue by izydorkowalsky** [bcgit/bc-csharp#222]
At the moment the key encryption algorithm, when generating a cms envelope, is taken from the subjectPublicKeyInfo of the recipients certificate.
It is not possible to set another padding scheme, e.g. RSAES-OAEP with parameters (like...sha256, mgf1sha256) to the KeyTransferRecipient.
Meanwhile decryption of encrypted data within an cms envelope with this padding scheme (created with NetCore 3.1) is possible and works well.

I tried changing the key encryption algorithm (hard coded) to "RSA//OAEPWITHSHA-256ANDMGF1PADDING. And added the appropriate algorithm and parameters to the KeyTransferRecipient.
This seemed to work: encryption parameters where set correctly, encryption was possible.
Decryption worked with BC api like a charm.

But when validating with other libraries the encrypted data couldn't be decrypted (OpenSSL, NetCore 3.1)

**Comment by jstedfast** [comment]
Could you check [MimeKit](https://github.com/jstedfast/MimeKit)'s latest development builds at [myget.org](https://www.myget.org/feed/mimekit/package/nuget/MimeKit) to see if this works for you? You'll need MimeKit 2.4.1.15 or later.

I *literally* just finished implementing RSAES-OAEP in MimeKit using BouncyCastle (had to override some classes to get it working).

Here's an example on how to do it:

```csharp
var message = new MimeMessage ();
message.From.Add (new MailboxAddress ("My Name", "me@mailhost.com"));
message.To.Add (new MailboxAddress ("Your Name", "you@mailhost.com"));
message.Subject = "Test of RSAES-OAEP w/ SHA-256 and MGF1 Padding";

var body = new TextPart ("plain") {
    Text = "This is the message body."
};

using (var ctx = new TemporarySecureMimeContext ()) {
    var recipients = new CmsRecipientCollection ();
    var recipient = new CmsRecipient (certificate) {
        EncryptiopnAlgorithms = new [] { EncryptionAlgorithm.Aes128 },
        RsaEncryptionPadding = RsaEncryptionPadding.OaepSha256
    };
    recipients.Add (recipient);

    var encrypted = ApplicationPkcs7Mime.Encrypt (ctx, recipients, body);
    message.Body = encrypted;
}

message.WriteTo ("message.eml");
```

**Comment by jstedfast** [comment]
This may be related: https://github.com/bcgit/bc-csharp/issues/161

**Comment by dghgit** [comment]
Full support for OAEP is now added, as is support for mixed-mode that the JVM native implementation still does. For the record common wisdom is currently that the MGF function should have the same level of security as the OAEP digest (or put simpler, make them the same). For full flexibility it is now possible to pass an OID and it's parameters to a KeyTransRecipientInfoGenerator which allows for the OAEP mixed mode should be appearing on github soon.
