### ISSUE TITLE
Bouncy Castle for C# package lib structure is not compatible with NuGet PackageReference format

### ISSUE THREAD

**Issue by dapatel** [bcgit/bc-csharp#224]
I’m working on a .Net application that is consuming BouncyCastle  v 1.8.5.  We are considering migrating to NuGet PackageReferences https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#package-compatibility-issues.  But migrating the project that consumes BouncyCastle is failing because BouncyCastle.Crypto.dll is directly in the lib folder of this package which is not supported as per above link - section " Assemblies in the lib root are ignored when the package is installed after the migration".  Is there a plan to repackage Bouncy Castle so that  the dll is under the supported target frameworks sub folder?

**Comment by onovotny** [comment]
Please use the Portable version from https://www.nuget.org/packages/Portable.BouncyCastle/ and that has all the required support.

**Comment by peterdettman** [comment]
https://www.nuget.org/packages/BouncyCastle.Cryptography is now available as the official NuGet.
