### ISSUE TITLE
[API Proposal]Add Memory<byte>/Span<byte> support.

### ISSUE THREAD

**Issue by ohsorry** [bcgit/bc-csharp#228]
[https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-3.1](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-3.1)

**Comment by ohsorry** [comment]
[Proposal 2] Add `chacha20-ietf-poly1305/xchacha20-ietf-poly1305` AEAD implementation.

**Comment by deniszykov** [comment]
Span/Memory and using shared buffers require re-writing huge portion of code. This repo has 2k C# files.
Also .NET 1.1/2/3/4.0 support will be dropped after this change.

**Comment by peterdettman** [comment]
Now available for many APIs under net6.0 in https://www.nuget.org/packages/BouncyCastle.Cryptography .

**Comment by aradalvand** [comment]
@peterdettman `BCrypt` and `OpenBsdBcrypt` APIs haven't been updated to take advantage of `Span<T>`.
