### ISSUE TITLE
DTLS client example

### ISSUE THREAD

**Issue by chkr1011** [bcgit/bc-csharp#245]
Hi,
I am looking for an example on how to setup a DTLS 1.2 Client which uses a PSK for authentication and TLS_PSK_WITH_AES_128_CCM_8. 

Unfortunately I was not able to find something especially in C#. Does anyone has some working sample (even written in Java). The files in this repo are just using mock services and I don't know how to migrate them.

Best regards
Christian

**Comment by jimsch** [comment]
There is a lot of junk around it, but https://github.com/Com-AugustCellars/CoAP-CSharp/tree/master/CoAP.NET/DTLS does this.

**Comment by chkr1011** [comment]
That looks promising. Thank you very much!
