### ISSUE TITLE
DefaultSignatureAlgorithmIdentifierFinder

### ISSUE THREAD

**Issue by RafikBeng** [bcgit/bc-csharp#250]
`algorithms["SHA256WITHECDSA"] = X9ObjectIdentifiers.ECDsaWithSha224;`
`algorithms["SHA512WITHECDSA"] = X9ObjectIdentifiers.ECDsaWithSha256;`
incorrect affectation

**Comment by dghgit** [comment]
Thanks for the report. Now fixed.
