### ISSUE TITLE
Signature verification fails after upgrading signing to BC 1.8.6.1

### ISSUE THREAD

**Issue by lemked** [bcgit/bc-csharp#252]
We have an API that verifies the signature of incoming API calls using RSASSA-PSS. For the signature generation on the client side, we're using BouncyCastle. This has been working fine with BC version 1.8.5 (and earlier versions), but has stopped working with version 1.8.6.1.

For verification, I've created two projects, one for signing a message and one for verifying the signature. I've been able to reproduce the issue that our API encounters, e.g. when signing and verifying the signature with version 1.8.5 everything is fine, but when I update the application that signs the message to 1.8.6.1, the application that verifies the signature, which still is on 1.8.5, will fail.

Source code and binary files have been attached. For reproducing the issue with the provided binary files (or your own compiled versions, where you are referencing the corresponding BC versions 1.8.5 and 1.8.6.1), you can generate a signature using Signer.exe and verify it via Verifier.exe:

- run 1.8.5 Signer.exe and copy output
- run 1.8.5 Verifier.exe and insert output => MATCH
- run 1.8.6.1 Signer.exe and copy output
- run 1.8.5 Verifier.exe and insert output => NO MATCH
- run 1.8.6.1 Signer.exe and copy output
- run 1.8.6.1 Verifier.exe and insert output => MATCH

I've also tried the following (hoping that it could be fixed on the API's side), same issue though:
- run 1.8.5 Signer.exe and copy output
- run 1.8.6.1 Verifier.exe and insert output => NO MATCH

So essentially, both sides must be using the same version or it won't work. That's not what I would have expected. Any ideas what is causing this effect? 

Source code for both applications is shown below.

**Signer.exe**
   ```csharp
    string message = "foo";
    byte[] bytesToSign = Encoding.UTF8.GetBytes(message);

    PemReader pemReader = new PemReader(new StringReader(File.ReadAllText("privateKey.pem")));
    object pemObject = pemReader.ReadObject();

    var pair = pemObject as AsymmetricCipherKeyPair;
    ICipherParameters parameters = pair.Private;

    int saltLength = 20;
    byte trailerField = 1;

    PssSigner pssSigner = new PssSigner(new RsaEngine(), new Sha256Digest(), saltLength, trailerField);
    pssSigner.Init(true, new ParametersWithRandom(parameters, new SecureRandom()));
    pssSigner.BlockUpdate(bytesToSign, 0, bytesToSign.Length);

    byte[] signature = pssSigner.GenerateSignature();

    string result = Convert.ToBase64String(signature);
```

**Verifier.exe**
   ```csharp
    string message = "foo";

    string signature = args[0];

    var fileStream = System.IO.File.OpenText("publicKey.pem");
    var pemReader = new Org.BouncyCastle.OpenSsl.PemReader(fileStream);
    var publicKey = (AsymmetricKeyParameter)pemReader.ReadObject();

    byte[] msgBytes = Encoding.UTF8.GetBytes(message);
    byte[] sigBytes = Convert.FromBase64String(signature);

    int saltLength = 20;
    byte trailerField = 1;

    PssSigner signer = new PssSigner(new RsaEngine(), new Sha256Digest(), saltLength, trailerField);
    signer.Init(false, publicKey);
    signer.BlockUpdate(msgBytes, 0, msgBytes.Length);

    var result = signer.VerifySignature(sigBytes);
```

Kind regards,
Daniel

**Comment by Neustradamus** [comment]
@dghgit, @dghbc, @peterdettman, @mwcw, @BlackthornYugen, @jstedfast, @timw, @rastrup, @avanpo, @fedelippo, @darkoperator, @agpreynolds, @ROM-Knowledgeware, @bartland, @ZZMarquis, @marcinpaszylk, @deniszykov, @beppler: Any news about this problem?

Thanks in advance.

@lemked, @bjguillot: Maybe a better place to contact bc-csharp team?

**Comment by peterdettman** [comment]
@lemked @Neustradamus
It appears the issue is caused by this fix: https://github.com/bcgit/bc-csharp/commit/57e5fa916b9cc641fb8897beb29179be0b518a1e#diff-2f5dd54d380fc82c30a6ddfeea83557d7fdfab5b52da16009a247f0cf67800ef .

You are specifying your own trailer byte of `0x01`, but in 1.8.5 that was ignored by a bugged constructor and the default `0xBC` used instead. When only one of the signer/verifier is upgraded, it gets the fix, but is now no longer using the default trailer.

Beyond upgrading both sides, or switching to the default trailer field, a third option is to use a non-bugged `PssSigner` constructor in 1.8.5:

```
IDigest digest = new Sha256Digest();
PssSigner pssSigner = new PssSigner(new RsaEngine(), digest, digest, saltLength, trailerField);
```

If the server code cannot be modified or BC updated, then it would have to be accepted that it is effectively using the default trailer, and clients would have to sign accordingly.

**Comment by lemked** [comment]
Thanks so much for your support @peterdettman ! We removed the trailer and are using the default trailer now, which solved the issue. What we don't understand yet: our API endpoint, as well as SDKs in other languages such as Java or PHP, are using our own trailer and work fine like that. We aren't sure why for the .NET implementation using the same custom trailer leads to this issue.

**Comment by peterdettman** [comment]
Presumably you have confused the default value of the "trailerField" INTEGER in the RSASSA-PSS-params ASN.1 structure (which is "1"), with it's meaning - which is to use the hexadecimal value 0xBC as the trailer field. See [RFC 4055 3.1](https://tools.ietf.org/html/rfc4055#section-3.1).
