### ISSUE TITLE
TLS 1.3 support?

### ISSUE THREAD

**Issue by sleeyax** [bcgit/bc-csharp#255]
Are there any plans to add TLS v1.3 anytime soon? I checked the `bc-java` repo and similar issues about it date back to 2018. 

Maybe I'm looking in the wrong places but there aren't many great TLS libraries out there for C#, so it would be great if bouncy castle gets an update on this!

**Comment by peterdettman** [comment]
It's loosely planned to port the latest bc-java TLS over to C# once TLS 1.3 is complete (it's about 90% done in bc-java), but I wouldn't like to guess at a date.

**Comment by meinname** [comment]
is there an updated schedule for this yet?
TLS 1.3 has been available in the Java version since last year.

**Comment by jojodat** [comment]
is there an updated schedule for this yet?
TLS 1.3 has been available in the Java version since last year.

**Comment by peterdettman** [comment]
I will be porting the latest Java TLS code to C# starting later this month.

**Comment by jojodat** [comment]
Sorry to bother again:  
Is there a preview/development repo to checkout and try the work in progress implementation?

**Comment by peterdettman** [comment]
I will be committing the more-or-less completed port to the main repo this weekend I expect.

**Comment by peterdettman** [comment]
After some delays the new TLS code is now committed (see Org.BouncyCastle.Tls namespace).

**Comment by jojodat** [comment]
thank you very much 👍
