### ISSUE TITLE
Loop when DTLS Handshakes fail or are aborted

### ISSUE THREAD

**Issue by patagonaa** [bcgit/bc-csharp#258]
If the RecordLayer is closed or there is an error while trying to receive data during the DTLS handshake (e.g. when the `RecordLayer.Receive()` throws an `IOException` or returns -1), `DtlsReliableHandshake.ReceiveMessage()` will loop forever and thus `DtlsServerProtocol.Accept()` will just block forever.

This is due to the fact that all `IOException`s are caught and the `TlsFatalAlert` (which is thrown when the RecordLayer is closed) also derives from IOException.

Looking at the release notes, this seems to have been fixed in the Java version since release 1.62:
> DTLS: Fixed infinite loop on IO exceptions.

#257 should fix this issue, but porting the changes from the Java version might still be a good idea in the long run, because it also adds an overall handshake timeout and other DTLS improvements.

**Comment by peterdettman** [comment]
Thanks for the report. Between #257 and the original Java fix we should be able to sort it out.

The Java (D)TLS code is actually quite far ahead of the C# version, and it is indeed our plan to re-port the latest Java code over to C#, but not before TLS 1.3 work is done. However I may make an exception and port the handshake timeout code over now if it is feasible.

**Comment by peterdettman** [comment]
We've released 1.8.7 which includes a fix for the infinite loop, plus support for an overall handshake timeout.

**Comment by patagonaa** [comment]
Works beautifully! Thank you a lot for the fix!
