### ISSUE TITLE
PGP encoding uses both old & new packet tags

### ISSUE THREAD

**Issue by rusty-boffin** [bcgit/bc-csharp#260]
Examining a PGP stream I noticed that the signature & onepass_signature packets are encoded using the old packet tag format (RFC1991), while the literal data packet is encoded using the new packet format. This seems to be a deliberate choice when calling BcpgOutputStream.WritePacket(), so I'm wondering if that's correct - shouldn't it always use the new format (RFC4880) when encoding?

**Comment by dghgit** [comment]
Yes, it's a deliberate choice. It's really for detached and cleartext signatures though - I don't think we've had any legacy complaints about encapsulated ones so we follow the "use new format where possible rule".
