### ISSUE TITLE
OpenSslPbeParameterGenerator support of different digest than MD5

### ISSUE THREAD

**Issue by LxWolfgang** [bcgit/bc-csharp#262]
OpenSsl let you define a specific Digest by using the -md parameter. (https://www.openssl.org/docs/manmaster/man1/openssl-enc.html)
Also MD5 isn't the default Digest anymore. In more recent versions of openssl the default digest ist SHA256.

The process of generating AES keys is the same but instead of using a MD5 hash it uses the specified one.
Because MD5 is outdated it is good practice to use more modern hashes.

It would be great if a additional constructor can be added that let you define the digest.
With that change I was able to generate the same key and iv just like openssl does.

**Comment by dghgit** [comment]
Thanks for the report. This is now added and should appear soon.
