### ISSUE TITLE
Dot net Core migration

### ISSUE THREAD

**Issue by Jkrockco** [bcgit/bc-csharp#265]
We are migrating existing .net framework encryption code that uses bouncy castle to .net core version. During the migration we are not able to find this function PgpUtilities.WriteFileToLiteralData in BouncyCastle.NetCore (1.8.6). Are there any equivalent functions available? Appreciate your help in advance.
Thanks

**Comment by Jooseba** [comment]
Hi,

We are having same problem. Cannot find PgpUtilities.WriteFileToLiteralData function.

**Comment by clairernovotny** [comment]
The package you should be using is `Portable.BouncyCastle`. That is the official .NET Core version. Does that have the functions you need?

**Comment by Jkrockco** [comment]
I will try, thanks for the guidance.

**Comment by peterdettman** [comment]
https://www.nuget.org/packages/BouncyCastle.Cryptography is now available, published directly by us (Legion of the Bouncy Castle Inc.).
