### ISSUE TITLE
Point Multiplication does not match NIST

### ISSUE THREAD

**Issue by BlackthornYugen** [bcgit/bc-csharp#272]
I tracked down a bug in my code to the Point Multiplication. I'm really not sure if I'm using the library incorrectly or if there is some kind of bug. I'm leaning towards it being an issue on my end because of how many of the test vectors fail.

I've created unit tests that reproduce this issue at:
https://github.com/BlackthornYugen/bc-csharp/tree/nist_tests

# Examples
## P256, k=5

Bouncy castle and NIST get: 

```
k = 5
x = 51590B7A515140D2D784C85608668FDFEF8C82FD1F5BE52421554A0DC3D033ED
y = E0C17DA8904A727D8AE1BF36BF8A79260D012F00D4D80888D1D0BB44FDA16DA4
```

## P256, k=6

Bouncy Castle: 

```
k = 6
x = 5E7E6865D210FF5C6813A818FE0CA5FFB4CAA280D7E9C1408CB9C2CAC8C7618F
y = A37E68D65CAD9E8BAE73D2120DA69552F50347C8B3BBED172730AC36428CBE67
```

NIST: 

```
k = 6
x = B01A172A76A4602C92D3242CB897DDE3024C740DEBB215B4C6B0AAE93C2291A9
y = E85C10743237DAD56FEC0E2DFBA703791C00F7701C7E16BDFD7C48538FC77FE2
```

# Test Code

```c#
public void TestMultiply(string curve, BigInteger k, BigInteger expectedX, BigInteger expectedY)
{
    // Arrange
    var x9EcParameters = Asn1.Nist.NistNamedCurves.GetByName(curve);

    // Act
    var ecPoint = x9EcParameters.G.Multiply(k);

    // Assert
    Assert.AreEqual(expectedX, ecPoint.XCoord.ToBigInteger(), "Unexpected X Coordinate");
    Assert.AreEqual(expectedY, ecPoint.YCoord.ToBigInteger(), "Unexpected Y Coordinate");
}
```

# Screenshots
## Test Result
![image](https://user-images.githubusercontent.com/3138467/96014465-6a456680-0e14-11eb-82c1-d4433e604f06.png)

## Test vector diff 
diff of crypto/test/data/bcnisttv.data and crypto/test/data/nisttv.data
![image](https://user-images.githubusercontent.com/3138467/96013648-80065c00-0e13-11eb-8ce9-1e56dd5ce8e9.png)

**Comment by peterdettman** [comment]
Probably you just need a call to `Normalize`:

```
var ecPoint = x9EcParameters.G.Multiply(k).Normalize();
````

Internally computations use an extra coordinate 'z' (read up on projective coordinates if you want to learn why). Before the x, y coordinates of a point can be compared to another implementation, or test vectors, the point needs to be converted into a canonical format. This is what the `Normalize` method does.

You might want to also access the x, y coordinates using the `AffineXCoord` and `AffineYCoord` properties, which will double-check that the `ECPoint` has been normalized.

**Comment by BlackthornYugen** [comment]
<3 Thank you! That did it!

![image](https://user-images.githubusercontent.com/3138467/96026211-396d2d80-0e24-11eb-83be-01eead54669b.png)

**Comment by BlackthornYugen** [comment]
If I updated my tests to follow the example of `crypto/test/src/crypto/test/SHA3DigestTest.cs`, would I be able to do a PR to add these tests?

Anyways, closing issue, mystery solved. Thanks for the tip on projective coordinates, I had no idea. :)

**Comment by BlackthornYugen** [comment]
I should have read the docs! You folks had a caution right there that I didn't read. 😅

```C#
/**
 * Returns the x-coordinate.
 * 
 * Caution: depending on the curve's coordinate system, this may not be the same value as in an
 * affine coordinate system; use Normalize() to get a point where the coordinates have their
 * affine values, or use AffineXCoord if you expect the point to already have been normalized.
 * 
 * @return the x-coordinate of this point
 */
public virtual ECFieldElement XCoord
```

**Comment by peterdettman** [comment]
> If I updated my tests to follow the example of `crypto/test/src/crypto/test/SHA3DigestTest.cs`, would I be able to do a PR to add these tests?
> 
> Anyways, closing issue, mystery solved. Thanks for the tip on projective coordinates, I had no idea. :)

Sure, we're happy to include extra test vectors.
