### ISSUE TITLE
DerUtcTime.ToAdjustedDateTime() fails for Apple Mail messages

### ISSUE THREAD

**Issue by jstedfast** [bcgit/bc-csharp#28]
Here's a link to the error encountered in MimeKit: https://github.com/jstedfast/MimeKit/issues/103

I think the problem is that the date encoded by Apple Mail has a seconds value of "60" (the value should probably be between 0 and 59, inclusive, if my understanding is correct for DateTime's parser).

I have a workaround in the most recent comment on that issue that basically rewrites DerUtcTime's ParseDateString() method to fixificate the hour/minute/second values and then re-serialize them back into a fixedDateStr string to pass to DateTime's parser (if we target .NET >= 3.5, that method could probably be fixed to parse out the TimeZone and use that, but in .NET <= 2.0, TimeZoneInfo does not exist so I don't know of a way of doing it other than hard-coding all known timezones).

**Comment by peterdettman** [comment]
A putative seconds value of 60 makes this an invalid UTCTime string. See X.680-0207 [1], 43.3 b) 2). Even if you were inclined to "accept" it, it still wouldn't be the canonical encoding that a signature requires. So, NotABug in BC, recommend you reject in MimeKit.

[1] http://www.itu.int/ITU-T/studygroups/com17/languages/X.680-0207.pdf

**Comment by jstedfast** [comment]
okay, thanks - I kinda figured as much, but wasn't sure.

**Comment by peterdettman** [comment]
Incidentally, it appears a GeneralizedTime would allow seconds=60, since it is defined by ISO 8601 [1], which appears to allow for a leap second, i.e. a distinct tick from the next 'mm00'. You'd still have to check that it was used appropriately, and "150213165460" does not strike me as a valid leap second!

[1] http://en.wikipedia.org/wiki/ISO_8601#Times

**Comment by jstedfast** [comment]
Indeed. According to WIkipedia:

    The most recent one happened on June 30, 2012 at 23:59:60 UTC.[1] A leap
    second will again be inserted at the end of June 30, 2015 at 23:59:60 UTC.[2]

**Comment by jstedfast** [comment]
Anyway, thanks for looking into this, Peter.

**Comment by peterdettman** [comment]
No problem. Will you report this against the responsible mail client?
