### ISSUE TITLE
Pkcs12Store - key and certificate with same alias

### ISSUE THREAD

**Issue by d11b** [bcgit/bc-csharp#280]
Hello,

I have a question regarding the Pkcs12Store class. I was provided with a pfx file containing both a certificate and a key. Both have the same alias. If I use `IsCertificateEntry` to figure out if the store contains a certificate it returns `false` even though a certificate with the passed alias exists. I found some suspicious code in the `IsCertificateEntry` method of Pkcs12Store.cs file.

The following code section of `IsCertificateEntry` returns `false` in case a certificate and a key with the same alias exist. 
`return (certs[alias] != null && keys[alias] == null);`
Here `certs[alias] != null` is `true` but `keys[alias] == null` is `false`

Pretty much the same logic is applied to the `IsKeyEntry` but with one exception:
`return (keys[alias] != null);`
Here it is not checked if a certificate exists with the same alias.

Is the check in `IsCertificateEntry()` done on purpose?

**Comment by dghgit** [comment]
Yes, if there's a certificate and a private key under the same alias, the entry is classified as a key entry (this is normally what it means, it's just that whoever generated the PKCS12 has assigned friendly names for both the certificate and the key). Things are classified as certificate entries when they only represent certificates with no associated keys.
