### ISSUE TITLE
OpenPGP feature flags are parsed incorrectly

### ISSUE THREAD

**Issue by filipnavara** [bcgit/bc-csharp#283]
The code that parses feature flags treats them at separate bytes instead of flags that are stored within one byte. Currently only one feature is supported, the modification detection packet, so both of these approaches produce identical results. However, OpenPGP 4880bis draft adds two new features (https://www.ietf.org/archive/id/draft-ietf-openpgp-rfc4880bis-10.html#section-5.2.3.25) and once implementations start using them the BouncyCastle code will incorrectly parse the results. This will inevitably lead to incorrect detection of the support of the modification detection packet and downgrading the security.

**Comment by dghgit** [comment]
Thanks for the heads up. I've fixed the processing and added the extra flags. I note that draft has expired and they appear to have moved to a different one now expiring in November. It's going to take some watching... Update should sync up soon.
