### ISSUE TITLE
DHParameters constructor checks

### ISSUE THREAD

**Issue by shrddr** [bcgit/bc-csharp#287]
I'm trying to connect (code [here](https://gist.github.com/shrddr/c25a1262b12239305b139935475a5989)) to `api.telegram.org` and the server provides these DH Parameters:

![image](https://user-images.githubusercontent.com/899919/107860102-87378800-6e4e-11eb-9665-9d95135c6ac5.png)

Deep inside `.Connect` call, a `DefaultTlsDHVerifier` [compares](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/tls/DefaultTlsDHVerifier.cs#L86) these against a set of [11 predefined](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/tls/DefaultTlsDHVerifier.cs#L25) parameter groups, and throws an error (code 71 aka `insufficient_security`) since it's not one of them¹. Okay guess I have to pass these values to a verifier constructor²: 

```
byte[] p = { 0x8b, 0xf9, 0x0d, 0x21, ... };
byte[] g = { 0x02 };
var groups = new List<DHParameters>{ new DHParameters(p, g) };
var verifier = new DefaultTlsDHVerifier(groups, 0);
```

But these values do not satisfy the requirement of **g <= p - 2** in DHParameters constructor because **p** is a negative number (leftmost bit is set). Why does C# version have this check when Java version doesn't?

Compare:
https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/parameters/DHParameters.cs#L86
https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/params/DHParameters.java#L86

¹Why do it? The way I see it, the server decides whatever parameters to use.
²What's the whole point of Verifier in this case? Can I safely skip it (`public override bool Accept(DHParameters _) => true;`)?

**Comment by dghgit** [comment]
P is not negative. The encodings are unsigned.
