### ISSUE TITLE
Support for curve25519 with TLS ECDSA

### ISSUE THREAD

**Issue by sipsorcery** [bcgit/bc-csharp#288]
Firstly, thanks for maintaining this library. A lot of open source .NET projects, including mine, would suffer without it.

I noticed the Java Bouncy Castle version has support for [curve25519](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/tls/src/main/java/org/bouncycastle/tls/NamedGroup.java#L53) with TLS ECDSA. Are there any plans to bring that support across to the C# version?

**Comment by peterdettman** [comment]
Both X25519 and Ed25519 are supported in current TLS code.
