### ISSUE TITLE
oid 2.5.4.4, surname as sn

### ISSUE THREAD

**Issue by borodjuka** [bcgit/bc-csharp#289]
I can't create 
`new X509Name("cn=Boro Djuka,serialNumber=CA:BA-9981816746,givenName=Boro,sn=Djuka,l=Banja Luka,c=BA")`
I get error

`Unknown object id - sn - passed to distinguished name`

It works if I use 'surname' instead of 'sn'
`new X509Name("cn=Boro Djuka,serialNumber=CA:BA-9981816746,givenName=Boro,surname=Djuka,l=Banja Luka,c=BA")`

Is it possible to add object id "sn" for oid 2.5.4.4 ?

**Comment by dghgit** [comment]
Sorry, we need to leave the long form here - people will get it confused with serialNumber otherwise... We actually did this in the Java build originally for serialNumber, it's now deprecated for that reason.
