### ISSUE TITLE
How to decrypt data using the BouncyCastle Blowfish implementation?

### ISSUE THREAD

**Issue by olaf-svenson** [bcgit/bc-csharp#293]
An external Api returns me the following Blowfish encrypted JSON body content
   `$-1$bb8ba9e30a19ff2a$c1157221764fe503d1fa9810fb9e6c3b424a1e8d014a321f5a2fb47ec6ebc8287d4d6236448d3623be42cf927fb883ca48810037c1a62bd229f937727c272c76420eb1f630bb2856c27d10c955220a1539f64e07c5708db90787ac370cad8372ea086501981c7d53ca69740c7ccfced856e234a6801efcf1f71178e75646441ba2716ea75a75ff3e6e002ba08ad18efeef95a909c9a5c68087cc63ed138a63c6788b9bbc43f3c04d2a496660f84ac98f011d3930c61ce9d5565131d2cba65db7c9bef824dd9a6594`

and I want to decrypt it with a given key e.g. `ab=cd`. I started with this method

        private string DecryptContent(string content, string decryptionKey)
        {
            BlowfishEngine blowfishEngine = new BlowfishEngine();
            PaddedBufferedBlockCipher paddedBufferedBlockCipher = new PaddedBufferedBlockCipher(blowfishEngine);
            
            byte[] decryptionKeyBytes = Encoding.UTF8.GetBytes(decryptionKey);

            paddedBufferedBlockCipher.Init(false, new KeyParameter(decryptionKeyBytes));

            byte[] encryptedContentBytes = Hex.Decode(content);

            int encryptedContentBytesAmount = paddedBufferedBlockCipher.GetOutputSize(encryptedContentBytes.Length);
            byte[] decryptedContentBytes = new byte[encryptedContentBytesAmount];

            int processedLength = paddedBufferedBlockCipher.ProcessBytes(encryptedContentBytes, 0, encryptedContentBytes.Length, decryptedContentBytes, 0);
            paddedBufferedBlockCipher.DoFinal(decryptedContentBytes, processedLength);

            return BitConverter.ToString(decryptedContentBytes);
        }

Unfortunately the code breaks at 

    byte[] encryptedContentBytes = Hex.Decode(content);

with the exception message

> invalid characters encountered in Hex data

I think this is because the `Decode` method expects a valid Base64 string and the content string contains invalid characters. Instead of using `Hex.Decode(content)` I tried to use `Encoding.UTF8.GetBytes(content);`. But then the code breaks at this line

    paddedBufferedBlockCipher.DoFinal(decryptedContentBytes, processedLength);

with the exception message

> last block incomplete in decryption

Would someone mind helping me fixing this decryption method?

---

Ok I just found out that this content seems to contain 3 parts when debugging it with this code

    Match matches = Regex.Match(encryptedContent, @"^\$([^$]{2,4})\$([a-f0-9]{16,64})\$([a-f0-9]*)");
    Group algorithm = matches.Groups[1];
    Group definition = matches.Groups[2];
    Group content = matches.Groups[3];

but I currently don't know how to continue with that...

**Comment by dghgit** [comment]
I'm sorry but you'll really need to ask whoever is generating it. Trying to guess through something like this can be the path to madness.
