### ISSUE TITLE
Not providing a TSA policy ID when generating a timestamp token throws a NullReferenceException

### ISSUE THREAD

**Issue by ndouthit** [bcgit/bc-csharp#295]
The TSA policy ID is optional per RFC 3161. If you try to generate a timestamp token with a null TSA policy ID, the TimeStampTokenGenerator throws a NullReferenceException on line 56 below.

https://github.com/bcgit/bc-csharp/blob/93b32a75656955faf7996d0f3e0ed391968d2ac6/crypto/src/tsp/TimeStampTokenGenerator.cs#L47-L56

If a DerObjectIdentifier object is not created and instead null is passed in (like in the code snippet below on line 126), trying to access tsaPolicy.Id will throw a NullReferenceException.

https://github.com/bcgit/bc-csharp/blob/93b32a75656955faf7996d0f3e0ed391968d2ac6/crypto/src/tsp/TimeStampTokenGenerator.cs#L117-L132

**Comment by dghgit** [comment]
Pull request associated with this now merged.
