### ISSUE TITLE
1.8 - expected release timeframe.

### ISSUE THREAD

**Issue by larsw** [bcgit/bc-csharp#30]
Hi,

 Are there any expectations when 1.8 stable will be released?

 Regards,

 Lars Wilhelmsen

**Comment by peterdettman** [comment]
We have just released 1.8.0-RC.1 (http://downloads.bouncycastle.org/betas/). We expect to release another one once we (hopefully) receive .NET CF 1.0 patches (see dev-crypto-sharp mailing list). Ideally, that would mean RC.2 a week from now, and a final release a week after that, assuming no regressions are found.

**Comment by dnauck** [comment]
Hi @peterdettman, any news on this issue: http://www.bouncycastle.org/jira/browse/BMA-107 ?

**Comment by larsw** [comment]
Ok, have you considered posting the beta/RC bits as prerelease Nugets (please) ?

**Comment by larsw** [comment]
A lot of .NET OSS projects have started to use AppVeyor (http://www.appveyor.com/) for Continuous Integration and publishing Nugets directly. AFAIK the service is free for OSS projects.

**Comment by koczkatamas** [comment]
+1 for adding PCL support. Minimal changes (only if you use PORTABLE comp. symbol), already done by @onovotny for the current codebase. (But be aware of GetBuffer vs. ToArray as ToArray copies the buffer while GetBuffer does not). 

So if add before 1.8 if you can. :)

**Comment by onovotny** [comment]
As an FYI, my portable fork is till tracking this repo and is also at 1.8 RC1. 

@koczkatamas as to the GetBuffer/ToArray differences, I am aware of them but I looked at the code paths and didn't see any places where the original buffer would be used after a mutation. It is important to be aware of though; the .net core profiles do not have a GetBuffer call so if mutation semantics are needed, we'd need to write a wrapper class that does the same thing. That said, I'm generally opposed to handing off a mutable buffer as that's just asking for trouble/race conditions later.

**Comment by peterdettman** [comment]
To update folks, we are currently intending to add PCL support for 1.8 (thanks @onovotny for maintaining an uptodate patch), and also still hope someone will step up to provide .NET CF compatibility. I had hoped to defer build system changes (including nuget publishing) until post-release, but that may not be ideal. We are probably still a couple of weeks away from a final release.

**Comment by onovotny** [comment]
@peterdettman Just as a btw, the PCL support now outputs two PCL libraries. One targets the widest range of platforms possible: net4, sl5, win8, wpa81, wp8. The other only targets modern platforms (net 45, win8, wpa81). 

The only minor change was a few places where "new reflection" had to be used in an ifdef. Also use of a Task.Run instead of a QUWI.

The reason for this is to enable support of .NET Native where compatible libraries need to target those newer platforms only.

**Comment by bartland** [comment]
Any chance it can include the changes I submitted to support sha256,etc using Pkcs5S2ParameterGenerator()? It's a very small change to one file, asn1/pkcs/PBKDF2Params.cs, that mirrors the Java implementation. Then I can stop maintaining a separate fork for my project.

**Comment by peterdettman** [comment]
@bartland Done.

**Comment by bartland** [comment]
@peterdettman Thanks so much. I and my organization/clients really appreciate it.

**Comment by Tol1** [comment]
Still waiting for release (or at least RC1 to nuget)

**Comment by onovotny** [comment]
I've added support for BC running on the CoreCLR

**Comment by peterdettman** [comment]
I've just built 1.8.0-RC.2 and it will find its way up onto the downloads page in the next day or so. We intend to release 1.8 stable after about 1 week, barring problems. We've closed out all the functionality changes we wanted to get in, so during this last week, I'm hoping to get updated Visual Studio project files, and to sort out PCL as best we can.

**Comment by onovotny** [comment]
Ok cool. I'll merge the latest into my fork. I've released a few interim updates, so I'm at rc4 or some such.

**Comment by onovotny** [comment]
BTW, have you pushed the latest to here? I'm getting a build error with CMSSignedDataGenerator line 140. 

Error	17	Argument 1: cannot convert from 'System.IO.Stream' to 'Org.BouncyCastle.Crypto.ISigner'	C:\Users\oren\Source\Git\BouncyCastle-PCL\crypto\src\cms\CMSSignedDataGenerator.cs	140	41	crypto.Net45

**Comment by larsw** [comment]
Ok, would be nice with a proper CI pipeline with pre release NuGets as well...

**Comment by onovotny** [comment]
I do have that setup too. https://ci.appveyor.com/project/onovotny/bouncycastle-pcl

There's a test failure I'm seeing as well.

**Comment by larsw** [comment]
Ok, found it; http://www.nuget.org/packages/Portable.BouncyCastle/

By the way, the number of different BC versions at nugert.org published by
misc people are a bit troublesome.

**Comment by onovotny** [comment]
Agreed, but not much that can be done with open source. In the end, I think people just wanted support on other platforms and went their own way.

My fork is aimed at being as close to the original as possible with the aim of it being mergable back in. Dunno about the others.

**Comment by bcgit** [comment]
Release candidate 2 is now up on http://www.bouncycastle.org/betas The github mirror should sync up shortly as well - you will know when it has as you'll see the tag for release-1.8.0-RC.2 arrive.

**Comment by peterdettman** [comment]
Release 1.8.0 is finally a wrap and will be available in the next day or so.

**Comment by peterdettman** [comment]
Actually, I should add that the initial release will just be of the "traditional" .NET 1.1 assembly (the last major release for which we're supporting it), although the build now includes alternate solution/project files for a variety of more modern frameworks/platforms. We intend to put up NuGet packages for some of these in due course.

**Comment by onovotny** [comment]
The 1.8.0 PCL NuGet is now live: http://www.nuget.org/packages/Portable.BouncyCastle/1.8.0
