### ISSUE TITLE
Time constructor always calling ToUniversalTime()

### ISSUE THREAD

**Issue by jspmu** [bcgit/bc-csharp#300]
It seems that when using Portable.BouncyCastle creating a new object of the Time class (Org.BouncyCastle.Asn1.X509) using a DateTime object as a parameter always calls ToUniversalTime() on the DateTime. 

This has caused some issues with certificates being generated an hour out when using gmt times and passing them into our X509V3CertificateGenerator.

``` 
public Time(
  DateTime date)
  {
#if PORTABLE
  string d = date.ToUniversalTime().ToString("yyyyMMddHHmmss", CultureInfo.InvariantCulture) + "Z";
#else
  string d = date.ToString("yyyyMMddHHmmss", CultureInfo.InvariantCulture) + "Z";
#endif

  int year = int.Parse(d.Substring(0, 4));

  if (year < 1950 || year > 2049)
  {
      time = new DerGeneralizedTime(d);
  }
  else
  {
      time = new DerUtcTime(d.Substring(2));
  }
}
```

**Comment by jspmu** [comment]
Apologies as we have looked into this issue further we actually found the source of the problem was Microsoft's X509Certificate2 (https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2?view=net-5.0) which when we created the X509Certificate2 object based on the certificate data generated by BouncyCastle it would in fact not interpret the date as Utc Time but as local time. Then the output object would have its NotBefore and NotAfter off by 1 hour.

This is now no longer an issue (at least with BouncyCastle) for us.

**Comment by peterdettman** [comment]
Thanks for following up.
