### ISSUE TITLE
Elliptic curve cryptography session key unwrap issue

### ISSUE THREAD

**Issue by Kusio** [bcgit/bc-csharp#306]
Hello guys,

Me and my team belive that there might be an issue regarding elliptic curve cryptography in bouncy castle .Net implementation.

1. What is the issue?
We have got a government institution which communicates with our system based on:
- ECDSA algorythm with SHA256 for SAML communicates
- Used curve: Nist Curve P-256
- Data cipher algorithm: AES256-GCM
- Session key cipher algorithm: AES256-KW
- Protocol used for key exchange: Key Agreement with ECDH-ES algorithm
Encryption is based on XML documents. We send message, they receive it properly. They send us response and around 1% of the messages they send us back is crashing on session key Unwrap step.

2. Practical example:
Let's say we have sent information out to the institution, they have responded with following message:  [FileToDecipher.log](https://github.com/bcgit/bc-csharp/files/6797212/FileToDecipher.log). This is an XML file so I advice so change ".log" to ".xml".

In the file we can see things like:
- Encryption Method of the assertion -> aes256-gmc
- Digest method of the assertion -> SHA256
- Encryption method of the key -> KW-AES256
- Agreement method -> ECDH-ES
- KDF Method -> ConcatKDF with SHA256Digest
- EC Key Value -> 
**Curve**: urn:oid:1.2.840.10045.3.1.7, 
**Public Key**: BDR7H//Ml3YjT0q3jVbq/csqWXyt2laNNYSl5SQRLxO1J4/Fhtp2ynCbRHkLd37vNCXJ0rLaFSAnRrvFbenOR1Q=
- Cipher data: q8FNkzjdxp5PLF9mHFXqUpNLl/MIDgGPVX0D/mg6xqGu3YgBKwV+YA==, this is an encrypted key used to then decipher Cipher value
- Cipher value is in the file but shouldnt matter for the example since it crashes on unwrap.

So we have got our application ready for deciphering the message. Below is the code we are using, I can even send you the application so you can run it yourselves if needed, but in case you would also need our priv certificate which should correlate to the public key send in the FileToDecipher, then we would need to ask permission from the client to send it. It shouldnt be a problem since that's just a test certificate, but still.

Since I cannot simply insert my project to the github issue I'll write out deciphering process step by step with code examples:
1. We retrieve private key parameters to the ECPrivateKeyParameters object:
```
private static ECPrivateKeyParameters GetPrivateKeyParameters(string idpEncryptionCertificateBase64Blob, string idpEncryptionCertificatePassword)
{
   using (MemoryStream stream = new MemoryStream(Convert.FromBase64String(idpEncryptionCertificateBase64Blob)))
   {
      using (StreamReader reader = new StreamReader(stream))
      {
         Pkcs12Store store = new Pkcs12Store(reader.BaseStream, idpEncryptionCertificatePassword.ToCharArray());

         foreach (string n in store.Aliases)
          {
             Console.WriteLine(n);
             if (store.IsKeyEntry(n))
             {
                AsymmetricKeyEntry asymmetricKey = store.GetKey(n);
                if (asymmetricKey.Key.IsPrivate)
                {
                   return asymmetricKey.Key as ECPrivateKeyParameters;
                }
              }
        }
     }
  }
   throw new Exception("Private key wasnt found");
}
```

2. We read ECPublicKeyParameters:
```
private static ECPublicKeyParameters GetPublicKeyParameters(string publicKeyData)
        {
            var wkEncryptionPublicKeyData = Convert.FromBase64String(publicKeyData);

            // urn:oid:1.2.840.10045.3.1.7 == secp256r1 -> https://www.alvestrand.no/objectid/1.2.840.10045.3.1.7.html
            var curve = ECNamedCurveTable.GetByOid(SecObjectIdentifiers.SecP256r1);
            var d = new ECDomainParameters(curve.Curve, curve.G, curve.N, curve.H);
            var p = curve.Curve.DecodePoint(wkEncryptionPublicKeyData);

            return new ECPublicKeyParameters(p, d);
        }
```
3. We calculate sharedSecret between public x private keys:
```
private static byte[] GetKeyAgreementAsByteArray(ECPrivateKeyParameters idpEncryptionPrivateKey, ECPublicKeyParameters wkEncryptionPublicKey)
        {
            IBasicAgreement aKeyAgree = AgreementUtilities.GetBasicAgreement("ECDH");
            aKeyAgree.Init(idpEncryptionPrivateKey);
            BigInteger sharedSecretInt = aKeyAgree.CalculateAgreement(wkEncryptionPublicKey);
            return sharedSecretInt.ToByteArrayUnsigned();
        }
```
4. We retrieve wrap key using KDF parameters:
```
 private static byte[] GetKeyCalculationInfo(string kdfAlgorithmID, string kdfPartyUInfo, string kdfPartyVInfo)
        {
            byte[] algorithmId = FromHexString(kdfAlgorithmID);
            byte[] partyUInfo = FromHexString(kdfPartyUInfo);
            byte[] partyVInfo = FromHexString(kdfPartyVInfo);

            byte[] keyCalculationInfo = new byte[algorithmId.Length + partyUInfo.Length + partyVInfo.Length];
            Array.Copy(algorithmId, keyCalculationInfo, algorithmId.Length);
            Array.Copy(partyUInfo, 0, keyCalculationInfo, algorithmId.Length, partyUInfo.Length);
            Array.Copy(partyVInfo, 0, keyCalculationInfo, algorithmId.Length + partyUInfo.Length, partyVInfo.Length);

            return keyCalculationInfo;
        }
```
5. We decipher session key with the use of wrap key
```
 private static byte[] GenerateDecryptionKey(byte[] wrapKey, string encryptedDecryptionKeyData)
        {
            var keyDecryptionAes = WrapperUtilities.GetWrapper(NistObjectIdentifiers.IdAes256Wrap);
            KeyParameter keyDecrtyptionParameters = new KeyParameter(wrapKey);
            keyDecryptionAes.Init(false, keyDecrtyptionParameters);

            var encryptedDecryptionKey = Convert.FromBase64String(encryptedDecryptionKeyData);

            // Unwrap method crashes
            return keyDecryptionAes.Unwrap(encryptedDecryptionKey, 0, encryptedDecryptionKey.Length);
        }
```

And here the method Unwrap crashes. The sad thing is that it crashes for around 1% of all the requests we recieve. 

Last things to note:
1. The code to generate XML file we need to decipher is written in JAVA:
- Version 1.8.0_111
- Bouncy castle version: bcprov-jdk15on 1.54
2. We spoke with client, sent them this file which failed on unwrap step on our side and they could decipher it properly using their java application.
3. I should also be able to send you the application the client used for deciphering the information on their side if needed.

Is there any way you can help us guys? Do you perhaps need more information from our side?

**Comment by peterdettman** [comment]
Try replacing:

`sharedSecretInt.ToByteArrayUnsigned()`

with:

`Org.BouncyCastle.Utilities.BigIntegers.AsUnsignedByteArray(aKeyAgree.GetFieldSize(), sharedSecretInt)`

**Comment by Kusio** [comment]
A quick test has shown that it indeed is the solution. 

I'm going to release it to our test environment which gets over 1k requests daily. If by the end of the day tomorrow I'll not get any data which causes unwrap issues I'll return to close the issue.

Thank you very much for quite a fast response. For the future, what exacly seems to be the difference between:
`sharedSecretInt.ToByteArrayUnsigned()`
and 
`Org.BouncyCastle.Utilities.BigIntegers.AsUnsignedByteArray(aKeyAgree.GetFieldSize(), sharedSecretInt)`

**Comment by peterdettman** [comment]
The replacement code gives you a fixed-size array, even if there will be leading zeros. The original code would give a shorter array when the agreement value happens to be small. This is why the failures are random (approx. 1 in 256 random agreements will be small enough to shorten the array by at least 1 byte).

**Comment by Kusio** [comment]
After release there are no more problems with unwrapping, thank you for your help!
