### ISSUE TITLE
Probelm with session_ticket Extension when use it

### ISSUE THREAD

**Issue by ahrzeroday** [bcgit/bc-csharp#316]
Hello,
when i use this code for adding session_ticket Extension to my client Hello :

`clientExtensions.Add(35, new byte[] { });`

i got this Error :

`TlsFatalAlert: decrypt_error(51)`

I don't know i use this code correct or not if not can you tell me correct way for adding session_ticket Extension to Client Hello,please?

thanks .

**Comment by peterdettman** [comment]
Your issue seems like it may be basically the same as this one: https://github.com/bcgit/bc-csharp/issues/317 (see comments there).
