### ISSUE TITLE
ECDsaSigner signature method parameters

### ISSUE THREAD

**Issue by basarugur** [bcgit/bc-csharp#322]
Hi, I have an issue regarding the `GenerateSignature` and `VerifySignature` methods of the `ECDsaSigner` class:
I think the `message` parameter in these methods is misleading, and something should be done about this. Although they are accepting a message of arbitrary length, they just truncate it according to the bit length of 'n' parameter. Therefore, I assume these methods are expecting the message digest/hash output. However, according to the referred standards (X9.62), hashing should actually be part of the signature generation and verification procedures. I also think that the intention with introducing the `CalculateE()` method was exactly this, but it just doesn't do any hashing. The whole class looks somewhat incomplete.

**Comment by peterdettman** [comment]
ECDsaSigner is usually used with DsaDigestSigner, which performs the hashing. The non-hashing versions are needed in some places where we need a raw signature operation. It could be organized differently, but we have inherited the Java API, for better or worse.
