### ISSUE TITLE
Memory leaks while reading crl

### ISSUE THREAD

**Issue by marcin022** [bcgit/bc-csharp#333]
Can anyone tell my what's wrong with this crl and why it can generate memory leaks ?

http://repo.e-dowod.gov.pl/crl/PLID_Authorization_CA_20201202.crl

![image](https://user-images.githubusercontent.com/7573905/141474009-e84b8347-1366-405b-809a-a99b49dbf019.png)

**Comment by peterdettman** [comment]
The CRL is quite large (though there are some really large ones out there), so significant memory usage of the loaded object should be expected. From a quick test there appear to be around 18,000 entries, corresponding to your counts of DerInteger, DerSequence, DerUTCTime. Could you explain why you are describing this as a memory leak as opposed to just number of heap objects?

By the way, there is the option to load CRLs lazily using `new X509CrlParser(true)` for the parsing. Lazy here means that the ASN.1 is not fully parsed until you drill down, so this may lower overall memory usage unless you are going to process the whole CRL anyway. You would probably want to make sure the CRL is validated by non-lazy parsing at least once though before "installing" it.

**Comment by marcin022** [comment]
thats was my mistake something else was source of memory leaks i already fix that. Thank you for your feedback and advice.
