### ISSUE TITLE
Upgrade from version 1.8.5 to 1.8.9 Issue

### ISSUE THREAD

**Issue by rashidhussainkhokhar** [bcgit/bc-csharp#335]
Hi,

Previously we were using version 1.8.5 and for the useless password we were passing **"".ToCharArray()** to **Pkcs12Store**. Now after upgrading to 1.8.9 I was getting an exception **password supplied for Keystore that does not require one**. 

So I have gone through the latest code and found out that we have a new property **IgnoreUselessPasswordProperty** which needs to be set in the Environment variable which fixed the issue but I would like to know more about this new property like what will be the impact of this and why it is necessary to set as an Environment variable.

**Comment by peterdettman** [comment]
The property simply allows to restore the old behaviour of ignoring that a "useless password" was provided. It is simpler to just pass null for the password when none is needed.
