### ISSUE TITLE
[Feature request] :Span<byte> as parameters for functions

### ISSUE THREAD

**Issue by Xyncgas** [bcgit/bc-csharp#339]
A lot functions are taking byte[]
using span<byte> instead can save allocations

**Comment by Xor-el** [comment]
While this is a good suggestion, I don't think this would fly as BouncyCastle support a lot of targets as far back as .NET framework (last I checked) which has no support for Span.

**Comment by Xyncgas** [comment]
Can't we have versions supporting only modern .NET thus allowing new features to be use.

You can increase the performance just by finding functions that works with byte[] from top to bottom and replace the parameter type with Span<Byte> and nothing in the user side of things needs to change.

However, if you can't have multiple versions of bouncy castle then maybe you can have a enviorment variable turing on and off functions that takes byte[] to Span<byte>

**Comment by yaakov-h** [comment]
You can't control type availability at runtime, it would have to be a separate assembly that targets a modern TFM or that takes a dependency on System.Memory.

**Comment by peterdettman** [comment]
@Xyncgas We are moving the whole project to .NET Standard imminently, so we will then be able to add these.

**Comment by Xyncgas** [comment]
> @Xyncgas We are moving the whole project to .NET Standard imminently, so we will then be able to add these.

Any updates?
