### ISSUE TITLE
Unresolved critical extensions issue in PkixCertPathChecker 

### ISSUE THREAD

**Issue by marcinpaszylk** [bcgit/bc-csharp#34]
When overriding Check method of PkixCertPathChecker.cs I can't remove unresolved critical extensions I don't want to check. 
Reson: unresolvedCritExts object is immutable ICollection.
Fix: It could be of type Org.BouncyCastle.Utilities.Collections.ISet, this way I can call Remove() method on collection.

**Comment by peterdettman** [comment]
Addressed by #35.
