### ISSUE TITLE
Support for EdDSA in PGP C#

### ISSUE THREAD

**Issue by ofrir-cl** [bcgit/bc-csharp#345]
Hello,

I am trying to decrypt a PGP message using a private key, but when using the function
`new PgpSecretKeyRingBundle(keyStream);`

I am getting the exception:
`unknown PGP public key algorithm encountered`

The private key has the algorithm as 0x16 (22) which should correspond to ed25519
Looks like a similar issue was fixed in the java version https://github.com/bcgit/bc-java/issues/636 so I am wondering if maybe it wasn't fixed in the C# one?

Thanks a lot in advance!

**Comment by peterdettman** [comment]
It has not yet been added to the C# build, but is on the TODO list.

**Comment by fnajera-rac-de** [comment]
The pull request #282 has worked for me. It also passes the corresponding Java tests (I've migrated them in https://github.com/fnajera-rac-de/bc-csharp/commit/f10df3af19ee74804399af39a1411628a05cde93).

**Comment by Indigo744** [comment]
I am particularly interested in this feature. Any ETA on this? Is there something I can do to help?
Thanks.

**Comment by mafia9874123** [comment]
Hi @peterdettman, how this issue going on? I'm having same issue when try to encrypt with public key type Ed25519

**Comment by peterdettman** [comment]
I've now ported the OpenPGP EdDSA (and XDH) support from bc-java. It will be in the v2 NuGet release this week.

**Comment by oseack** [comment]
> I've now ported the OpenPGP EdDSA (and XDH) support from bc-java. It will be in the v2 NuGet release this week.

Hi Peter, did this happen? I look forward to your reply. I really appreciate your help.

**Comment by LeoMiguelB** [comment]
I am also curious on the current status of this.

**Comment by ofrir-cl** [comment]
Can confirm this was added in v2
