### ISSUE TITLE
Any updates on allowing use of span in the library?

### ISSUE THREAD

**Issue by Xyncgas** [bcgit/bc-csharp#349]
https://github.com/bcgit/bc-csharp/issues/339
For example, if I have a pointer instead of byte array, I would like to create a span and use it as AES KEY instead of having to create a new managed array from the datas that the pointer points to because I can not use the pointer directly therefore having to use a copy of it

**Comment by peterdettman** [comment]
https://www.nuget.org/packages/BouncyCastle.Cryptography is now available. There are now Span-based alternatives for many APIs when using net6.0.
