### ISSUE TITLE
Adds authorization information access to the certificate

### ISSUE THREAD

**Issue by qq1176914912** [bcgit/bc-csharp#352]
Why can't I find an instance to add authorization information access to the certificate?

**Comment by qq1176914912** [comment]
If I want to generate a certificate with OCSP, do I need to add the extension 'authorization information access' to the certificate?

**Comment by harrison314** [comment]
@qq1176914912 use the `Org.BouncyCastle.Asn1.X509.AuthorityInformationAccess` class and its instance in the certificate generator `Org.BouncyCastle.X509.X509V3CertificateGenerator`.
