### ISSUE TITLE
Extract OCSP reponses from CmsSignedData

### ISSUE THREAD

**Issue by sorinteican** [bcgit/bc-csharp#357]
Exception while trying to extract OCSPBasic data from the SignedData.crls. RFC 5652 (https://datatracker.ietf.org/doc/html/rfc5652#page-36) defines the crls structure as:

RevocationInfoChoices ::= SET OF RevocationInfoChoice

   RevocationInfoChoice ::= CHOICE {
     crl CertificateList,
     other [1] IMPLICIT OtherRevocationInfoFormat }

OtherRevocationInfoFormat ::= SEQUENCE {
     otherRevInfoFormat OBJECT IDENTIFIER,
     otherRevInfo ANY DEFINED BY otherRevInfoFormat }

**Comment by peterdettman** [comment]
I added `OtherRevocationInfoFormat `support from another PR today, so this may now be fixed. Please open a new issue if the problem persists.
