### ISSUE TITLE
CcmBlockCipher implementation is not streamable

### ISSUE THREAD

**Issue by k3d3** [bcgit/bc-csharp#36]
It appears the CcmBlockCipher implementation has a fake interface, and states that CCM is a packet mode.

This isn't quite true; the CTR stream cipher itself is not only streamable, but seekable to the byte (for reads - seeking writes is dangerous), and the CMAC tag used allows streaming accumulation of the MAC to eventually output as a tag.

**Comment by peterdettman** [comment]
We'd be open to a patch, but don't really have the resources for this ourselves. Also, retaining backward compatibility could be tricky since the existing implementation allows additional data and plaintext to be processed (buffered) in any order. So there are broader consequences to any changes.

**Comment by k3d3** [comment]
> We'd be open to a patch, but don't really have the resources for this ourselves.

That's fair enough - I might take a stab at implementing it.

> Also, retaining backward compatibility could be tricky since the existing implementation allows additional data and plaintext to be processed (buffered) in any order.

It appears that on calls to ProcessBytes, it's appending to an internal data buffer. In this case, I believe it's still sensitive to order.

Thank you for the response.

**Comment by timw** [comment]
You can't init the mac in CCM mode until you know the length of the data, and you can't process data in the mac until you've processed all AD (the first block `b_0` processed by the CBC MAC (not a CMAC) includes the data length `l(m)`, and if associated data is included the next block contains the length of the AD `l(a)`).

If you could provide the data length ahead of time (e.g. in init via custom params), and the AD ahead of any encryption, then you could provide data to CCM without buffering (with the caveat that @peterdettman notes about existing ability to add AD interleaved with data), but by the time you've handled all these complexities you're probably better off just using EAX (which has a very similar structure, but solves all these problems already).

If you're just wanting to avoid buffering, then extending processPacket to take the AD and supplying everything all at once would work. If you're doing something like encrypting large files where you can pre-determine the size and AD but still want to stream data in _and_ absolutely have to use CCM, then it might be worth the required trickery.

**Comment by k3d3** [comment]
I see, thank you for the info.

>  If you're doing something like encrypting large files where you can pre-determine the size and AD but still want to stream data in and absolutely have to use CCM, then it might be worth the required trickery.

This is actually my case right now, however it doesn't seem universal enough that it could be implemented in BC.
