### ISSUE TITLE
InvalidCipherTextException: mac check in GCM failed when use BouncyCastle in Unity

### ISSUE THREAD

**Issue by milad-ahmadi** [bcgit/bc-csharp#362]
Hi,
I want to use BouncyCastle in Unity 2019.04.08 with Api compatibility level  .NET standard 2.0 or .NET 4.x. 
when use GcmBlockCipher, I get the following error:
InvalidCipherTextException: mac check in GCM failed
Org.BouncyCastle.Crypto.Modes.GcmBlockCipher.DoFinal

I tried different versions of BouncyCastle but it did not change:
[BouncyCastle](https://www.nuget.org/packages/BouncyCastle/)
[BouncyCastle.NetCore](https://www.nuget.org/packages/BouncyCastle.NetCore/)
[Portable.BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle/)
[Portable.BouncyCastle-GOST2012](https://www.nuget.org/packages/Portable.BouncyCastle-GOST2012/)

When I run the same code with VS 2015 with .NET Framework 4, the code runs without error.

**Comment by peterdettman** [comment]
Probably this issue is obsolete, but if someone still sees a similar problem, please open a new issue (but it would need sample code/data at least).

**Comment by shinnthant-lab** [comment]
Dear @peterdettman , I just faced the issue with .net 7 bouncy castle latest version.
Please see the below snippet for your reference.

key, iv and associated data all the way same as encrypt method.

Best Regards,

`var keyParam = new KeyParameter(Key);
IBlockCipher cipher = new AesEngine();


int macSize = 8 * cipher.GetBlockSize();
byte[] nonce = IV;
byte[] associatedText = Encoding.ASCII.GetBytes("test.com");
AeadParameters keyParamAead = new AeadParameters(keyParam, macSize, nonce, associatedText);
GcmBlockCipher cipherMode = new GcmBlockCipher(cipher);
cipherMode.Init(false, keyParamAead);

int outputSize = cipherMode.GetOutputSize(cipherText.Length);
byte[] plainTextData = new byte[outputSize];
int result = cipherMode.ProcessBytes(cipherText, 0, cipherText.Length, plainTextData, 0);
cipherMode.DoFinal(plainTextData, result);
return Encoding.UTF8.GetString(plainTextData);`

**Comment by peterdettman** [comment]
I would need a complete example, including all the data involved. I'm also not clear on what the problematic environment is supposed to be.
