### ISSUE TITLE
BC can't read SM2 crl, can you help me?

### ISSUE THREAD

**Issue by 390620652** [bcgit/bc-csharp#367]
I try to use these code below to read crl, it's Ok to read the crl with RSA, but it's not worked for crl with SM2. 
Is anyother way to read crl with SM2?
Please help me to resolve the problem.   Thank you.
`
byte[] buf = File.ReadAllBytes(path);
            X509CrlParser xx = new X509CrlParser();
            X509Crl ss = xx.ReadCrl(buf);
            var nextupdate = ss.NextUpdate;
`

**Comment by peterdettman** [comment]
It would be very helpful to have an example CRL to test against.

**Comment by 390620652** [comment]
> 
[two crl.zip](https://github.com/bcgit/bc-csharp/files/9100128/two.crl.zip)
thank you

**Comment by 390620652** [comment]
> It would be very helpful to have an example CRL to test against.
[two crl.zip](https://github.com/bcgit/bc-csharp/files/9100339/two.crl.zip)
here is two kinds of crl .

**Comment by peterdettman** [comment]
The difference is that file `sm2.crl` is base64-encoded, which `rsa.crl` is not.

After adding this line, `sm2.crl` loads fine:
```
buf = Org.BouncyCastle.Utilities.EncodersBase64.Decode(buf);
```
