### ISSUE TITLE
Can not decrypt string 32 characters and longer using Rijndael = "pad block corrupted"

### ISSUE THREAD

**Issue by mrdat222** [bcgit/bc-csharp#369]
I'm having problems decrypting, after encrypting, a string that is 32 characters or longer. I tried to debug the code to fix, but I'm not sure what would need to be fixed. I think I did find that when the plainText is 32 characters or more, the first 32 bytes of the buffer gets overwritten with what would have been the 2nd 32 bytes of code, instead of the offset index starting at 31 to continue decrypting. (Hope that makes sense).

Below is a .NET Framework based test console application that loops and creates string starting with 31 character and going up. The 2nd iteration will fail inside BC and gets "pad block corrupted".

using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Crypto.Digests;
using Org.BouncyCastle.Crypto.Engines;
using Org.BouncyCastle.Crypto.Generators;
using Org.BouncyCastle.Crypto.Modes;
using Org.BouncyCastle.Crypto.Paddings;
using Org.BouncyCastle.Crypto.Parameters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BCEncryption32PlusIssue
{
    internal class Program
    {
        static string key = "";
        static string iv = "";
        static string characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=,./<>?;':[]{}`~\"";

        static void Main(string[] args)
        {
            key = GenerateKeyIv("123456");
            iv = GenerateKeyIv("987654");

            for (int i = 30; i < characters.Length; i++)
            {
                try
                {
                    string plainText = characters.Substring(0, i + 1);

                    (string encryptedBase64, byte[] encryptedByteArray) = Encrypt(plainText, key, iv);
                    try
                    {
                        (string decrypted, byte[] decryptedByteArray) = Decrypt(encryptedBase64, key, iv);

                        if (decrypted == plainText)
                            Console.WriteLine($"Decrypted fine. Size: {plainText.Length}");
                        else
                            Console.WriteLine($"Decrypted failed.");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Decrypted failed. -> {ex.Message}");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"{ex}");
                }
            }
        }

        public static string GenerateKeyIv(string pass)
        {
            string result = string.Empty;

            PbeParametersGenerator generator = new Pkcs5S2ParametersGenerator();
            generator.Init(PbeParametersGenerator.Pkcs5PasswordToUtf8Bytes((pass).ToCharArray()), Encoding.UTF8.GetBytes("789456"), 1000);
            KeyParameter key = (KeyParameter)generator.GenerateDerivedParameters("AES", 256);

            result = Convert.ToBase64String(key.GetKey());
            return result;
        }

        public static (string base64, byte[] byteArray) Encrypt(string textToEncrypt, string key, string iv)
        {
            if (textToEncrypt == null)
            {
                throw new ArgumentNullException(nameof(textToEncrypt));
            }
            var ivStringBytes = Convert.FromBase64String(iv);
            var cipherTextBytes = Encoding.UTF8.GetBytes(textToEncrypt);

            var keyBytes = Convert.FromBase64String(key);
            var engine = new RijndaelEngine(256);
            var blockCipher = new CbcBlockCipher(engine);

            var cipher = new PaddedBufferedBlockCipher(blockCipher, new Pkcs7Padding());
            var keyParam = new KeyParameter(keyBytes, 0, 32);
            var keyParamWithIV = new ParametersWithIV(keyParam, ivStringBytes, 0, 32);
            cipher.Init(true, keyParamWithIV);
            var outputBytes = new byte[cipher.GetOutputSize(cipherTextBytes.Length)];
            var length = cipher.ProcessBytes(cipherTextBytes, outputBytes, 0);
            var finalBytes = cipher.DoFinal(outputBytes, 0, length);
            var final = Convert.ToBase64String(finalBytes);
            return (final, finalBytes);
        }
        public static (string base64, byte[] byteArray) Decrypt(string cipherText, string key, string iv)
        {
            if (cipherText == null)
            {
                throw new ArgumentNullException(nameof(cipherText));
            }
            var ivStringBytes = Convert.FromBase64String(iv);
            var cipherTextBytes = Convert.FromBase64String(cipherText);

            var keyBytes = Convert.FromBase64String(key);
            var engine = new RijndaelEngine(256);
            var blockCipher = new CbcBlockCipher(engine);
            var cipher = new PaddedBufferedBlockCipher(blockCipher, new Pkcs7Padding());
            var keyParam = new KeyParameter(keyBytes, 0, 32);
            var keyParamWithIV = new ParametersWithIV(keyParam, ivStringBytes, 0, 32);
            cipher.Init(false, keyParamWithIV);
            var outputBytes = new byte[cipher.GetOutputSize(cipherTextBytes.Length)];
            var length = cipher.ProcessBytes(cipherTextBytes, outputBytes, 0);
            var finalBytes = cipher.DoFinal(outputBytes, 0, length);
            var final = Encoding.UTF8.GetString(finalBytes);
            return (final, finalBytes);
        }
    }
}

**Comment by dghgit** [comment]
I don't believe these exist in the BC API:

        var length = cipher.ProcessBytes(cipherTextBytes, outputBytes, 0);
        var finalBytes = cipher.DoFinal(outputBytes, 0, length);

that said the problem is probably due to the DoFinal using 0 instead of length. It's throwing away the output from the first step.

**Comment by mrdat222** [comment]
Thanks for the reply!

I'm new to BC and don't have a lot of experience with encryption outside of our current implementation using .NET Framework's built in. 

I've tried different lengths and with and without DoFinal (which seems to not be needed if the original value is exactly 32 characters.

Could you provide me any guidance on how I should find the right values? Any poking in the right direction would be helpful. Thanks!
