### ISSUE TITLE
PGPSecretKey does not support unicode pass phrases

### ISSUE THREAD

**Issue by Meddington** [bcgit/bc-csharp#37]
If a passphrase contains an umlaut (ä, ö, ü, Ü, Ä, Ö, ß, ...), the key cannot be extracted/unlocked.  The problem can be traced into PgpUtilities.MakeKeyFromPassPhrase which calls Strings.ToByteArray.  Strings.ToByteArray will convert a char[] passphrase string into bytes assuming a 1-to-1 mapping of chars to bytes.  In reality these functions should probably use the Encoding classes to perform such conversions so proper encoding can be taken into account such as UTF-8.

Code flow:

PGPSecretKey::ExtractPrivateKey(passPhrase)
PGPSecretKey::ExtractKeyData(passPhrase)
PgpUtilities.MakeKeyFromPassPhrase(..., passPhrase)
Strings.ToByteArray(passPhrase)

**Comment by Muraad** [comment]
It seems it is already know at least for the java version http://bouncy-castle.1462172.n4.nabble.com/checksum-mismatch-at-0-of-20-while-trying-to-extract-PGP-Secret-Key-with-Umlaut-PIN-created-by-gnupg-td4657144.html

But it also seems there is no standard for the passphrase encoding. So the "solution" is to (brute force) try all, or the most common encodings. 
Maybe it is enough to make a MakeKeyFromPassPhrase overload that takes an Encoding as argument, and leave it to the caller how to handle encoding failures? 

It´s used in 3 places https://github.com/bcgit/bc-csharp/search?utf8=%E2%9C%93&q=PgpUtilities.MakeKeyFromPassPhrase

**Comment by Muraad** [comment]
Hmm... "GNUPG assumes UTF-8 for PKCS#12 passwords unless a locale (e.g. Latin1, CP850) has been explictly set with --p12-charset.  Utilities like gpgsm are a bit more clever/worse and try a whole bunch (unless —p12-charset is set). See minip12.c; function decrypt_block; it will try the local locale/raw, ISO-8859-1, 15, 2,3, 4 - 9, KOI8, IBM437, 850, EUC, and BIG5. Most other utils just try utf8, the locale and then iso_8859-1(5). All in that order. And in each case it will clean any mess found - by re-encoding where needed as proper utf8 or UCS-2 in BMP when a charset is specified. "

**Comment by peterdettman** [comment]
We've added alternative versions of various methods that accept a passphrase; xxxUtf8 that converts it to bytes using Encoding.UTF8, and xxxRaw which just accepts a byte[] directly, allowing external handling of encoding issues.

e.g. PgpSecretKey.ExtractPrivateKeyUtf8 and PgpSecretKey.ExtractPrivateKeyRaw
