### ISSUE TITLE
CMS Unit tests - SignedDataTests.cs TestSha1WithRsaAndAttributeTable() uses the wrong cert to perform the signature

### ISSUE THREAD

**Issue by antiduh** [bcgit/bc-csharp#38]
[SignedDataTests.cs][1] is one of the CMS unit test files. `TestSha1WithRsaAndAttributeTable()` is one of the unit tests that steps through the full procedure of picking a full certificate chain to sign a simple message with, producing a detached signature, and then verifying the signature.

The test uses two certificates defined/created by the test harness - `OrigCert` and `SignCert`.

Here is how they are created:
```C#
		private static X509Certificate OrigCert
		{
			get { return origCert == null ? (origCert = CmsTestUtil.MakeCertificate(OrigKP, OrigDN, OrigKP, OrigDN)) : origCert; }
		}

		private static X509Certificate SignCert
		{
			get { return signCert == null ? (signCert = CmsTestUtil.MakeCertificate(SignKP, SignDN, OrigKP, OrigDN)) : signCert; }
		}
```

And here is where they are included in the certificate chain as part of the signature process.
```C#
    IList certList = new ArrayList();
    certList.Add(OrigCert);
    certList.Add(SignCert);
```

From the names of the properties, and how the certs they represent are constructed, it would seem that `OrigCert` is supposed to be a root cert - it is self signed, and it is used to issue `SignCert`. Presumably, `SignCert` then is used to sign the payload - the 'hello world' message in the test.

The problem is that when the signature is generated in the test, `SignCert` is not used to generate the signature - `OrigCert` is used instead:

```C#
gen.AddSigner(OrigKP.Private, OrigCert, CmsSignedDataGenerator.DigestSha1,
    new AttributeTable(v), null);
```

This probably was supposed to use `SignCert`, not `OrigCert`, since it doesn't make practical sense to include a subordinate cert when signing a message with a cert higher in the chain; this signature could've been completed all the same without the statement `certList.Add(SignCert);`.

[1]: https://github.com/bcgit/bc-csharp/blob/master/crypto/test/src/cms/test/SignedDataTest.cs

**Comment by peterdettman** [comment]
Thanks, I've changed the test to use SignCert which makes more sense.
