### ISSUE TITLE
How to use Blowfish algorithm. Can I help me!

### ISSUE THREAD

**Issue by HauTC-DevXamarin-MAUI** [bcgit/bc-csharp#382]
May I ask you something ?
How to encrypt and decrypt any content using the blowfish algorithm. Can you give me an example?
Tks!

**Comment by dghgit** [comment]
The test classes are a useful place to find examples. If you look at:

https://github.com/bcgit/bc-csharp/blob/master/crypto/test/src/crypto/test/BlowfishTest.cs

and it's base class you will see how it works.
