### ISSUE TITLE
"long form definite-length more than 31 bits" during Pkcs12Store Load

### ISSUE THREAD

**Issue by ASt1101** [bcgit/bc-csharp#385]
Hi Team Bouncy Castle,

I have an issue while trying to load a P12 keystore.

The Load method raises an exception "long form definite-length more than 31 bits".
Could you give any hints why this is happening and how to get rid of it?

` Pkcs12Store p12 = new Pkcs12Store();
            using (var stream = File.OpenRead(filename))
                p12.Load(stream, pin.ToArray()); //this is where the exception is raised`
            
This is the content of the keystore shown by KeyStore Explorer:
![grafik](https://user-images.githubusercontent.com/114064781/191465489-d95dff4d-e5c3-44fb-b562-b13df5d108a8.png)

Thanks for your help.
Regards,
Axel

**Comment by peterdettman** [comment]
It means malformed ASN.1, either for the keystore itself (probably not), or because an incorrect password was specified so that data didn't decrypt correctly into valid ASN.1.
