### ISSUE TITLE
Publish .NET Standard compatible version to NuGet

### ISSUE THREAD

**Issue by JuanuMusic** [bcgit/bc-csharp#393]
Hey there. It looks like the version on nuget is not compiled for .net standard 2.0 or 2.1, however, when I cloned the repository it seems to be set up with .net standard.

Do we need to upload the latest version to github?

**Comment by peterdettman** [comment]
It's definitely built for netstandard2.0.

It also shows netstandard2.0 here:
https://www.nuget.org/packages/BouncyCastle.Cryptography#supportedframeworks-body-tab

and the package contents definitely include an assembly in lib/netstandard2.0:
https://nuget.info/packages/BouncyCastle.Cryptography/2.0.0

so I am unclear what you could mean by "not compiled for .NET standard 2.0".

**Comment by DeshSa01** [comment]
@peterdettman Any reason we don't have a std 2.1 version included? Can we just compile the latest to multi-target 2.1 and net472 and use?
