### ISSUE TITLE
Encrypt/Decrypt in PHP compatible with Bouncy Castle

### ISSUE THREAD

**Issue by rbaenar** [bcgit/bc-csharp#394]
Hello

I am trying to make requests to a web service, but the request data must be encrypted with AES-256-GCM. The library that the web service uses to encrypt and decrypt is Bouncy Castle, but I am programming in PHP.

I have done many tests, I have consulted dozens of blogs, but I can't find how I can do the encryption in PHP so that Bouncy Castle decrypts it correctly.

Please can you help me on this matter? Do you have any PHP example to encrypt and decrypt with AES-256-GCM that is compatible with Bouncy Castle?

I really appreciate your help.

**Comment by zerobit00000** [comment]
I am currently working on a similar issue.  Were you able to find a PHP solution for Bouncy Castle AES-256-GCM?  If so, could you share it here?

**Comment by cipherboy** [comment]
@rbaenar or @zerobit00000 Likely you will get some mileage out of [`openssl_encrypt`](https://www.php.net/manual/en/function.openssl-encrypt.php), which has an AES-GCM mode. However, if you have compatibility issues, please open a new issue or reply to this one with test keys, data, and PHP & C# code and we can help debug interoperability issues.
