### ISSUE TITLE
S/MIME: Certificate has unsupported critical extension (EKU)

### ISSUE THREAD

**Issue by boomer41** [bcgit/bc-csharp#395]
We are verifying S/MIME signatures with MailKit in combination with BouncyCastle in C#.
We stumbled upon a subscriber certificate (which we unfortunately can't share), which has the EKU extension set to S/MIME, and its criticality is set.

BouncyCastle C# fails with the exception `Org.BouncyCastle.Pkix.PkixCertPathValidatorException: Certificate has unsupported critical extension`.

As noted in 2019 on StackOverflow [1], there seems to be a discrepancy between the Java version and the C# version.
This holds true as of today.
In the Java version, the EKU extension gets removed from the set of critical extension [2].
The equivalent line is missing in the C# version [3]. 

As this critical extension should be handled correctly, and I don't know if BC C# has full support for EKUs, I don't wanna patch the C# version blindly for our purposes.
Are there any reasons for this discrepancy?
Would it be safe remove this discrepancy?

[1] https://stackoverflow.com/a/57752867
[2] https://github.com/bcgit/bc-java/blob/d98b7cd8a05ced51c272c99a8706a7a9b4e88a46/prov/src/main/java/org/bouncycastle/jce/provider/PKIXCertPathValidatorSpi.java#L477
[3] https://github.com/bcgit/bc-csharp/blob/b03a3283f3c1cc258db6a5697074c86071a40233/crypto/src/pkix/PkixCertPathValidator.cs#L406

**Comment by peterdettman** [comment]
Sorry for the delayed response. I have now added the missing line for ExtendedKeyUsage. 2.1.0 will be out soonwith the fix.

**Comment by boomer41** [comment]
As 2.2.1 is already published on nuget seemingly containing the fix, i think this issue can be closed? :)

**Comment by peterdettman** [comment]
Yes, thanks. Fixed in 2.1.0.
