### ISSUE TITLE
x509Name not converting embedded commas correctly

### ISSUE THREAD

**Issue by GermanAndresVargasTorres** [bcgit/bc-csharp#408]
I am attempting to generate a Certificate Signing Request where one of the Organizational Unit values that must go in the subject contains an embedded comma:

OU=BANCO BILBAO VIZCAYA ARGENTARIA, S.A

If this is written verbatim in the [dirName](https://csharp.hotexamples.com/examples/Org.BouncyCastle.Asn1.X509/X509NameEntryConverter/-/php-x509nameentryconverter-class-examples.html#0x7dc2968835eb997513d6c49e85bd4f8699ffef44b7e2c1144587c0ce5dc8c650-582,,675,), BouncyCastle will correctly throw a "badly formated directory string" ArgumentException. Following the advice from [this link](https://qa.social.msdn.microsoft.com/Forums/windows/en-US/2a20e7d1-6565-40e0-95b4-ec32aeac2930/resolving-a-x509-certificate-with-embedded-commas-in-the-subject?forum=wcf), this OU value must be written delimited by quotes, which I have attempted in two different ways:

`string subjectTest1 = "OU=\"BANCO BILBAO VIZCAYA ARGENTARIA, S.A\"";      // OPTION 1 - Using a string escape sequence`
`string subjectTest2 = @"OU=""BANCO BILBAO VIZCAYA ARGENTARIA, S.A""";     // OPTION 2 - Using a verbatim string literal`

However, when checking the resulting subject name, an additional backslash is being added before the comma:

![image](https://user-images.githubusercontent.com/6863031/209563343-17e67f06-c585-4845-ad63-d1c918463322.png)

¿Has someone encountered this problem before? If so, ¿how were you able to solve it?

**Comment by peterdettman** [comment]
If you try adding other values to the subject, you will see that comma is used as a separator between RDNs in `X509Name.ToString()`, so we have to include the escape character to avoid confusion.

However you shouldn't be using `ToString` for anything other than simple presentation scenarios; there is an API for enumerating RDNs. e.g.:

```
string subjectTest = "OU=\"BANCO BILBAO VIZCAYA ARGENTARIA, S.A\"";
var x509Name = new X509Name(subjectTest);
foreach (var v in x509Name.GetValueList(X509Name.OU))
{
    Console.WriteLine(v);
}
```

which prints:

> BANCO BILBAO VIZCAYA ARGENTARIA, S.A
