### ISSUE TITLE
Move to netstandard TFM

### ISSUE THREAD

**Issue by clairernovotny** [bcgit/bc-csharp#41]
Moving this issue here from https://github.com/onovotny/BouncyCastle-PCL/issues/12

This is to move from `dotnet` to `netstandard` in the nuspec. See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md for details.

The nuspec will be greatly simplified as it required extra blank dependency groups and copies of the libs in platform-specific TFM `\lib` dirs. to work correctly.

This issue is dependent on https://github.com/dotnet/corefx/issues/4367 being completed.

/cc @peterdettman

**Comment by onovotny** [comment]
@peterdettman I have pushed a packaging update to the `1.8.1` version that includes support for `netstandard`.

https://github.com/onovotny/BouncyCastle-PCL/tree/pcl-netstandard

I plan on releasing this as 1.8.1.1 to the `Portable.BouncyCasltle` package on Monday so that people can more easily use it with .NET Core.

**Comment by VanCoding** [comment]
Can you maybe also add the "netcoreapp" framework? I want to use BouncyCastle from my .NET Core application that uses this framework and I can't currenty depend on it because it says:

```
    Package Portable.BouncyCastle 1.8.1 is not compatible with netcoreapp1.6 (.N
ETCoreApp,Version=v1.6). Package Portable.BouncyCastle 1.8.1 supports:
      - dotnet (.NETPlatform,Version=v5.0)
      - monoandroid (MonoAndroid,Version=v0.0)
      - monotouch (MonoTouch,Version=v0.0)
      - net45 (.NETFramework,Version=v4.5)
      - net46 (.NETFramework,Version=v4.6)
      - portable-monoandroid10+monotouch10+net40+sl5+win8+wp8+wpa81+xamarinios10
+xamarinmac20 (.NETPortable,Version=v0.0,Profile=net4+sl5+wp8+win8+wpa81+MonoTou
ch10+MonoAndroid10+xamarinmac20+xamarinios10)
      - portable-monoandroid10+monotouch10+net45+win8+wpa81+xamarinios10+xamarin
mac20 (.NETPortable,Version=v0.0,Profile=net45+win8+wpa81+MonoTouch10+MonoAndroi
d10+xamarinmac20+xamarinios10)
      - uap10.0 (UAP,Version=v10.0)
      - win8 (Windows,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios (Xamarin.iOS,Version=v0.0)
      - xamarinmac (Xamarin.Mac,Version=v0.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.6.
```

And it seems that "netcoreapp" is the recommended framework to use for .NET Core applications, so this will be needed in the future anyways.

**Comment by onovotny** [comment]
`netcoreapp` is only for executables and applications, not libraries. `netcoreapp` currently supports `netstandard1.6`: https://docs.microsoft.com/en-us/dotnet/articles/standard/library#net-platforms-support

**Comment by VanCoding** [comment]
@onovotny But... how would I use BouncyCastle from a `netcoreapp` - application then?

And should BouncyCastle already support `netstandard1.6`? Because if I try to restore with it, it still says that BouncyCastle does not support it.

**Comment by onovotny** [comment]
Any higher netstandard level can use lower level ones. Right now you also need an `imports` statement because there's no published version that has `netstandard` support. That's coming shortly.

**Comment by VanCoding** [comment]
Nice! The imports statement works fine, thank you :)

**Comment by onovotny** [comment]
v1.8.1.1 is now on NuGet with netstandard support

**Comment by nothingmn** [comment]
Any chance we can move this to netstandard1.4.  Since this is a library which others will rely on, having it as low as it possibly can be will guaranteed a larger population of projects which can leverage this library.

**Comment by onovotny** [comment]
As an update, v1.8.1.2 is updated on NuGet that adds a net4 version and is authenticode signed to ensure origin.

**Comment by onovotny** [comment]
@nothingmn `Portable.BouncyCastle` is targeting `netstandard1.3` with full functionality. That means that any library that's `netstandard1.3` or higher can reference it.

**Comment by John0King** [comment]
When will #68  merge ?

**Comment by peterdettman** [comment]
As of just now, the official package is https://www.nuget.org/packages/BouncyCastle.Cryptography, with support for net461, netstandard2.0 and net6.0.
