### ISSUE TITLE
throw e; instead of throw;

### ISSUE THREAD

**Issue by santiago-ribero** [bcgit/bc-csharp#425]
In the files below, there are exceptions that are caught and re-thrown with the following structure:

```
void RootOperation()
{
    try
    {
        OperationA();
        OperationB();
    }
    catch (Exception e)
    {
        throw e;
    }
}
```

When the Exception is caught outside the RootOperation(), its stack trace shows "at RootOperation()" as the origin of the exception. As you may know, if `throw e;` is replaced with `throw;`, the stack trace of the exception will allow to determine if it was originally thrown by `OperationA()` or `OperationB()`.

Is there any reason why it was decided to use `throw e;` ?
Would you consider replacing it with `throw;` ?

Files containing `throw e;` :

- crypto/src/cms/CMSSignedHelper.cs
- crypto/src/cms/SignerInformation.cs
- crypto/src/openpgp/PgpPbeEncryptedData.cs
- crypto/src/openpgp/PgpPublicKey.cs
- crypto/src/openpgp/PgpPublicKeyEncryptedData.cs
- crypto/src/openpgp/PgpSecretKey.cs
- crypto/src/openpgp/PgpUtilities.cs
- crypto/src/openssl/PEMReader.cs
- crypto/src/openssl/PEMWriter.cs
- crypto/src/tls/ClientHello.cs
- crypto/src/tls/DtlsClientProtocol.cs
- crypto/src/tls/DtlsRecordLayer.cs
- crypto/src/tls/DtlsServerProtocol.cs
- crypto/src/tls/DtlsTransport.cs
- crypto/src/tls/RecordStream.cs
- crypto/src/tls/TlsProtocol.cs
- crypto/src/tls/TlsUtilities.cs
- crypto/src/tls/crypto/impl/TlsAeadCipher.cs
- crypto/src/tls/crypto/impl/bc/BcTlsECDomain.cs
- crypto/src/x509/X509CrlParser.cs
- crypto/src/x509/X509V2AttributeCertificate.cs

Thank you.

**Comment by peterdettman** [comment]
Thanks for the report. I guess these were inherited from bc-java, where those are rethrows (e.g. see https://weblogs.asp.net/bhouse/272297).

I have reviewed all throws that weren't "throw new...", which includes all the ones you list, and changed all appropriate instances to a simple throw (rethrow).
