### ISSUE TITLE
Wrong Subnet Calculation from Cidr

### ISSUE THREAD

**Issue by martinbu** [bcgit/bc-csharp#426]
Hi,
I think this should be a left-shift?

https://github.com/bcgit/bc-csharp/blob/830d9b8c7bdfcec511bff0a6cf4a0e8ed568e7c1/crypto/src/asn1/x509/GeneralName.cs#L340

Example: a cidr of 12 will result in a subnetmask of 255.15.0.0 instead of 255.240.0.0

**Comment by peterdettman** [comment]
Indeed. Fixed and added unit test coverage.

Bug not present in bc-java. Apparently diverged before git migration.
