### ISSUE TITLE
AttributePkcs vs AttributeX509

### ISSUE THREAD

**Issue by larsw** [bcgit/bc-csharp#43]
Hi,

 Just out of curiosity, aren't these semantically the same (and origin from the same ASN.1 specification) ?

**Comment by bcgit** [comment]
Sort of... the reason for the duplication is that PKCS#7 defined it's own version, this is reflected in the CMS RFCs as well so we ended duplicating the object in case it diverged in a later edition of the standards. We may have been over cautious on this one, but when the class was introduced over 10 years ago, it wasn't really clear what was going to happen.
