### ISSUE TITLE
string SM3WITHSM2 not an OID

### ISSUE THREAD

**Issue by bian8021** [bcgit/bc-csharp#431]
I used following code to create sm2 algorithm CSR with following code:

var pkcs10CertificationRequest = new Pkcs10CertificationRequest("SM3WITHSM2", subjectName, sm2KeyPair.Public, null, sm2KeyPair.Private);

but I get following error:: 
string SM3WITHSM2 not an OID

what is the issue?

**Comment by peterdettman** [comment]
The registry to lookup an OID doesn't currently have an entry for "SM3WITHSM2". I have now added it. In the meantime you could just pass the OID directly instead of the name: `Org.BouncyCastle.Asn1.GM.GMObjectIdentifiers.sm2sign_with_sm3.Id` .
