### ISSUE TITLE
new BigInteger("340​282​366​920​938​463​463​374​607​431​768​211​455") incorrect format error

### ISSUE THREAD

**Issue by aaelick** [bcgit/bc-csharp#433]
Strange error. There is nothing wrong with this number. Same error in System.Numerics namespace also.

**Comment by peterdettman** [comment]
The string as pasted in the PR title contains zero-width spaces (https://util.unicode.org/UnicodeJsps/character.jsp?a=200B), which are not valid decimal characters.
