### ISSUE TITLE
exception: 'Scalar is not in the interval [1, n - 1] (Parameter 'd')' while reading private key string to private key

### ISSUE THREAD

**Issue by bian8021** [bcgit/bc-csharp#435]
I have a private key string, I want to read it into private key:

            byte[] data = Convert.FromBase64String(privateKeyString); 
            BigInteger privateKey = new BigInteger(data);

            // 根据BigInteger类型私钥创建ECPrivateKeyParameters对象            
           ECPrivateKeyParameters privateKeyParams = new ECPrivateKeyParameters(privateKey, sm2Parameters);

once the code execute the create ECPrivateKeyParameters instance, it throw 
exception: 'Scalar is not in the interval [1, n - 1] (Parameter 'd')'

what is the issue?

**Comment by peterdettman** [comment]
Try this instead:
 `BigInteger privateKey = new BigInteger(1, data);`

**Comment by bian8021** [comment]
same error

**Comment by peterdettman** [comment]
Please show value of `privateKeyString`.

**Comment by bian8021** [comment]
MIICSwIBADCB7AYHKoZIzj0CATCB4AIBATAsBgcqhkjOPQEBAiEA/////v////////////////////8AAAAA//////////8wRAQg/////v////////////////////8AAAAA//////////wEICjp+p6dn140TVqeS89lCafzl4n1FauPkt28vUFNlA6TBEEEMsSuLB8ZgRlfmQRGajnJlI/jC7/yZgvhcVpFiTNMdMe8Nzai9PZ3nFm9zuNraSFT0KmHfMYqR0AC3zLlITnwoAIhAP////7///////////////9yA99rIcYFK1O79Ak51UEjAgEBBIIBVTCCAVECAQEEIM54Akk7zC5veBYEtjZgMTH0dkO7K9NLyQRqbKN/JQzRoIHjMIHgAgEBMCwGByqGSM49AQECIQD////+/////////////////////wAAAAD//////////zBEBCD////+/////////////////////wAAAAD//////////AQgKOn6np2fXjRNWp5Lz2UJp/OXifUVq4+S3by9QU2UDpMEQQQyxK4sHxmBGV+ZBEZqOcmUj+MLv/JmC+FxWkWJM0x0x7w3NqL09necWb3O42tpIVPQqYd8xipHQALfMuUhOfCgAiEA/////v///////////////3ID32shxgUrU7v0CTnVQSMCAQGhRANCAATkGZtlJFYIlM/og/P+jRF5CezMal+mrLtuIZVfT8KnwPa0mInGoswtt1aXJo+0Y3tPVJgUF6wILnHLHkeFvYxo

**Comment by bian8021** [comment]
@peterdettman here is my private key string:

MIICSwIBADCB7AYHKoZIzj0CATCB4AIBATAsBgcqhkjOPQEBAiEA/////v////////////////////8AAAAA//////////8wRAQg/////v////////////////////8AAAAA//////////wEICjp+p6dn140TVqeS89lCafzl4n1FauPkt28vUFNlA6TBEEEMsSuLB8ZgRlfmQRGajnJlI/jC7/yZgvhcVpFiTNMdMe8Nzai9PZ3nFm9zuNraSFT0KmHfMYqR0AC3zLlITnwoAIhAP////7///////////////9yA99rIcYFK1O79Ak51UEjAgEBBIIBVTCCAVECAQEEIM54Akk7zC5veBYEtjZgMTH0dkO7K9NLyQRqbKN/JQzRoIHjMIHgAgEBMCwGByqGSM49AQECIQD////+/////////////////////wAAAAD//////////zBEBCD////+/////////////////////wAAAAD//////////AQgKOn6np2fXjRNWp5Lz2UJp/OXifUVq4+S3by9QU2UDpMEQQQyxK4sHxmBGV+ZBEZqOcmUj+MLv/JmC+FxWkWJM0x0x7w3NqL09necWb3O42tpIVPQqYd8xipHQALfMuUhOfCgAiEA/////v///////////////3ID32shxgUrU7v0CTnVQSMCAQGhRANCAATkGZtlJFYIlM/og/P+jRF5CezMal+mrLtuIZVfT8KnwPa0mInGoswtt1aXJo+0Y3tPVJgUF6wILnHLHkeFvYxo

**Comment by bian8021** [comment]
@peterdettman here is the code to generate private key string, the last line code is the private key string:

static void GenerateCsrAndPrivateKey(string commonName, string country, string state, string city, string organization, string unit, string email, string password)
{
      X9ECParameters x9ECParameters = GMNamedCurves.GetByName("sm2p256v1");
    ECDomainParameters sm2Parameters = new ECDomainParameters(x9ECParameters.Curve, x9ECParameters.G, x9ECParameters.N);

// Generate an SM2 key pair
    var sm2KeyPairGenerator = new ECKeyPairGenerator();
    var sm2KeyGenerationParameters = new ECKeyGenerationParameters(sm2Parameters, new SecureRandom());
    sm2KeyPairGenerator.Init(sm2KeyGenerationParameters);
    var sm2KeyPair = sm2KeyPairGenerator.GenerateKeyPair();


    // Create a PKCS#10 certificate signing request (CSR) for the public key
    var subjectName = new X509Name($"CN={commonName}, C={country}, ST={state}, L={city}, O={organization}, OU={unit}, E={email}");
    var pkcs10CertificationRequest = new Pkcs10CertificationRequest(GMObjectIdentifiers.sm2sign_with_sm3.Id, subjectName, sm2KeyPair.Public, null, sm2KeyPair.Private);

    // Save the CSR to a file
    using (var csrFileWriter = new StreamWriter("csr.pem"))
    {
        var pemWriter = new PemWriter(csrFileWriter);
        pemWriter.WriteObject(pkcs10CertificationRequest);
        pemWriter.Writer.Flush();
    }
    string csr = Convert.ToBase64String(pkcs10CertificationRequest.GetEncoded());

    var pkInfo = PrivateKeyInfoFactory.CreatePrivateKeyInfo(sm2KeyPair.Private);
    string privateKey = Convert.ToBase64String(pkInfo.GetDerEncoded());

    // Output the private key to a file
    ECPrivateKeyParameters privateKey1 = (ECPrivateKeyParameters)sm2KeyPair.Private;
    PrivateKeyInfo privateKeyInfo = PrivateKeyInfoFactory.CreatePrivateKeyInfo(privateKey1);
    byte[] privateKeyBytes = privateKeyInfo.GetEncoded();
    string privateKeyBase64 = Convert.ToBase64String(privateKeyBytes);

}

**Comment by peterdettman** [comment]
To retrieve the private key from the base64 encoding:

``` csharp
byte[] pk2Bytes = Convert.FromBase64String(privateKeyBase64);
var pk2 = PrivateKeyFactory.CreateKey(pk2Bytes);
```

Also I suggest to create key generation parameters like this instead:

``` csharp
new ECKeyGenerationParameters(GMObjectIdentifiers.sm2p256v1, new SecureRandom());
```

**Comment by bian8021** [comment]
thank you, it works
