### ISSUE TITLE
System.IO.IOException: 'unexpected packet in stream: ' for Public-Key Encrypted Session Key

### ISSUE THREAD

**Issue by dhaven** [bcgit/bc-csharp#436]
When I try to read a PGP message which contains a Public-Key Encrypted Session Key I get the error message: **System.IO.IOException: 'unexpected packet in stream: '** 

With the following PGP message in binary format: [193,94,3,45,185,208,183,54,93,229,221,18,1,7,64,28,103,55,88,116,186,18,206,0,68,88,68,101,113,237,234,176,198,229,155,232,35,103,18,53,238,124,136,130,107,16,39,48,117,235,162,201,115,115,33,123,66,54,129,185,141,193,85,212,0,144,107,119,41,49,156,58,202,104,246,181,75,204,33,225,194,14,97,208,97,244,248,98,56,44,70,139,155,79,26,239]

I expect the following code snippet to correctly parse the message:
```c#
MemoryStream contentKeyPacket_ms = new MemoryStream(new byte[] { 193, 94, 3, 45, 185, 208, 183, 54, 93, 229, 221, 18, 1, 7, 64, 28, 103, 55, 88, 116, 186, 18, 206, 0, 68, 88, 68, 101, 113, 237, 234, 176, 198, 229, 155, 232, 35, 103, 18, 53, 238, 124, 136, 130, 107, 16, 39, 48, 117, 235, 162, 201, 115, 115, 33, 123, 66, 54, 129, 185, 141, 193, 85, 212, 0, 144, 107, 119, 41, 49, 156, 58, 202, 104, 246, 181, 75, 204, 33, 225, 194, 14, 97, 208, 97, 244, 248, 98, 56, 44, 70, 139, 155, 79, 26, 239 });
Stream contentKeyPacket_s = PgpUtilities.GetDecoderStream(contentKeyPacket_ms);
PgpObjectFactory fac = new PgpObjectFactory(contentKeyPacket_s);
PgpObject nextObj = fac.NextPgpObject() => throws the error
```

The same PGP message can correctly be parsed using openpgp.js readMessage() function.

**Comment by peterdettman** [comment]
The data appears to contain only an isolated "Public-Key Encrypted Session Key Packets (Tag 1)", which we can parse.

However the PgpObjectFactory is processing higher-level constructs, in this case a PgpEncryptedDataList, which is one or more session keys followed by a data packet (being the data encrypted by the session key).

I suppose if you want to parse individual packets for yourself you should be using BcpgInputStream directly.

**Comment by dhaven** [comment]
Thanks for that clarification.

Can you please advice on how to create a BcpgInputStream? It doesn't seem to have any public constructor and I also can't extract it from the PgpObjectFactory object.

Thank you,

**Comment by peterdettman** [comment]
Sorry yeah, it's actually not designed to be exposed, I spoke too soon. I guess you could propose some change to support just low-level packet parsing, but it's not really what the current API is designed for. Also it's better for us to drive OpenPGP changes from the bc-java version, which is usually ahead of the bc-csharp one.

**Comment by dhaven** [comment]
Thanks for your answer. I ended up going in the other direction and appending the encrypted data packet to the encrypted session key and I got successful results from the NextPgpObject() function. (I also managed to decrypt the data packet which is what I was looking to do all along.)

Thanks again for pointing that out it helped me tremendously.
