### ISSUE TITLE
NullReferenceException during DTLS handshake

### ISSUE THREAD

**Issue by patagonaa** [bcgit/bc-csharp#458]
I'm finally using the BouncyCastle version with DTLS connection ID (v2.2.0) in a productive environment and I've stumbled across weird exceptions with some clients:

```
Org.BouncyCastle.Tls.TlsFatalAlert: internal_error(80) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Org.BouncyCastle.Tls.AbstractTlsServer.GetServerExtensionsForConnection(IDictionary`2 serverExtensions)
   at Org.BouncyCastle.Tls.DtlsServerProtocol.GenerateServerHello(ServerHandshakeState state, DtlsRecordLayer recordLayer)
   at Org.BouncyCastle.Tls.DtlsServerProtocol.ServerHandshake(ServerHandshakeState state, DtlsRecordLayer recordLayer, DtlsRequest request)
   at Org.BouncyCastle.Tls.DtlsServerProtocol.Accept(TlsServer server, DatagramTransport transport, DtlsRequest request)
```

Sadly, I don't have more details about where exactly this exception is thrown, but I suspect it has to do with the new code for negotiating the connection ID extension.

Also, other connections work fine, so I assume it might have something to do with the clients doing something weird, because from what I can tell, all "legitimate" connections are working.

**Comment by patagonaa** [comment]
Update: I have captured packets from the server and it seems like this happens with clients that do not have any client extensions in their ClientHellp. I'll take a look at it and add a PR if I find something.

**Comment by peterdettman** [comment]
It will be this line:
https://github.com/bcgit/bc-csharp/blob/b3684bb62499d52cdea3c0cad82f001462a22b50/crypto/src/tls/AbstractTlsServer.cs#LL607C21-L607C21

As a workaround you should be able to override the method and duplicate it, adding a null check on m_clientExtensions.

**Comment by patagonaa** [comment]
I've now added a PR for the null check.
Thank you for the workaround, I hadn't thought of that.

**Comment by peterdettman** [comment]
Fixed by https://github.com/bcgit/bc-csharp/pull/459 .
