### ISSUE TITLE
Unit tests in binary distribution

### ISSUE THREAD

**Issue by Genbox** [bcgit/bc-csharp#47]
When installing BouncyCastle 1.7.0 from NuGet, all the unit tests are included in the binary distribution, making the distribution larger than it needs to be. What are the reasons for including the unit tests?

**Comment by jstedfast** [comment]
This should no longer be the case for 1.8.0 as both Oren and I removed the unit tests from the Visual Studio project files and moves them into UnitTests.csproj

**Comment by Genbox** [comment]
Thought the source control was different from the build scripts used for binary distribution as the tests were included in the dist, but separate in the source control. I consider this issue closed.

**Comment by peterdettman** [comment]
Thanks guys. I'll just add that any NuGet packages of 1.7.0 were not built by us, although at least in one case we gave our approval to supply one.
