### ISSUE TITLE
KyberPrivateKeyParameters reconstructed from encoded string not the same as original

### ISSUE THREAD

**Issue by kxrna** [bcgit/bc-csharp#477]
## Background

I'm relatively new to the cryptography space, so apologies in advance if there is something obvious I am missing.

I was playing around with the Kyber implementations in the library, and wanted to test out serialization and deserialization after the initial key pair generation.

I found that the public parameter reconstruction from a Base64 string works (equality comparison matches), but could not say the same for the private parameters.

## Code
Here is the code I am playing around with:

```csharp

    public static void Main(string[] args)
    {
        var random = new SecureRandom();

        // generating key pair
        var kpGenParams = new KyberKeyGenerationParameters(random, KyberParameters.kyber768);
        var kpGen = new KyberKeyPairGenerator();
        kpGen.Init(kpGenParams);
        var keyPair = kpGen.GenerateKeyPair();

        // parsing out private and public params
        var privateParams = (KyberPrivateKeyParameters)keyPair.Private;
        var publicParams = (KyberPublicKeyParameters)keyPair.Public;

        // START - faux deserialization for comparison
        // var privPkcs8 = PqcPrivateKeyInfoFactory.CreatePrivateKeyInfo(privateParams).GetEncoded();
        var privPkcs8 = PqcPrivateKeyInfoFactory.CreatePrivateKeyInfo(privateParams).ToAsn1Object().GetDerEncoded();
        // var pubPkcs8 = PqcSubjectPublicKeyInfoFactory.CreateSubjectPublicKeyInfo(publicParams).GetEncoded();
        var pubPkcs8 = PqcSubjectPublicKeyInfoFactory.CreateSubjectPublicKeyInfo(publicParams).ToAsn1Object().GetDerEncoded();

        var privPkcs8InB64 = Convert.ToBase64String(privPkcs8);
        var pubPkcs8InB64 = Convert.ToBase64String(pubPkcs8);

        var privateParams2 = (KyberPrivateKeyParameters)PqcPrivateKeyFactory.CreateKey(Convert.FromBase64String(privPkcs8InB64));
        var publicParams2 = (KyberPublicKeyParameters)PqcPublicKeyFactory.CreateKey(Convert.FromBase64String(pubPkcs8InB64));

        Console.WriteLine($"Public Comparison: {Arrays.AreEqual(publicParams.GetEncoded(), publicParams2.GetEncoded())}");
        Console.WriteLine($"Private Comparison: {Arrays.AreEqual(privateParams.GetEncoded(), privateParams2.GetEncoded())}");
        // END - faux deserialization for comparison

        // generate shared secret and encapsulated cipher text
        var kemGenerator = new KyberKemGenerator(random);
        var secretWithEncapsulation = kemGenerator.GenerateEncapsulated(publicParams2);
        var rawSecret = secretWithEncapsulation.GetSecret();
        var cipherText = secretWithEncapsulation.GetEncapsulation();

        // make extractor with private params and get secret
        var kemExtractor = new KyberKemExtractor(privateParams2);
        var extractedSecret = kemExtractor.ExtractSecret(cipherText);

        Console.WriteLine($"\n\nGenerated Symmetric Key: {Hex.ToHexString(rawSecret)}\nRetrieved Symmetric Key: {Hex.ToHexString(extractedSecret)}");

        var secretsEqual = Arrays.AreEqual(rawSecret, extractedSecret);
        Console.WriteLine($"Secrets Equal ---> {secretsEqual}");
    }
```

The issue is that the `Public Comparison` always yields `True`, but the `Private Comparison` always yields `False`. Accordingly, when I instantiate the `KyberKemGenerator` as follows:

```charp
var kemExtractor = new KyberKemExtractor(privateParams2);
```

The `secretsEqual` always yields `False`. However, when I instantiate the `KyberKemGenerator` as:

```csharp
var kemExtractor = new KyberKemExtractor(privateParams);
```

The `secretsEqual` indeed yields `True`.

## Sample Output

Here is some sample output to illustrate more clearly.

### Using `privateParams` (Original private parameters from generated key pair)

```
Public Comparison: True
Private Comparison: False


Generated Symmetric Key: cbd9fc141e6c8e2c9baa3e2a14174f67184f6f7205801e9754b7e6aa3d922845
Retrieved Symmetric Key: cbd9fc141e6c8e2c9baa3e2a14174f67184f6f7205801e9754b7e6aa3d922845
Secrets Equal ---> True
```

### Using `privateParams2` (Reconstructed private parameters from Base64 string)

A note here, I've tried using both:

```csharp
   var privPkcs8 = PqcPrivateKeyInfoFactory.CreatePrivateKeyInfo(privateParams).GetEncoded();
```
and...

```csharp
   var privPkcs8 = PqcPrivateKeyInfoFactory.CreatePrivateKeyInfo(privateParams).ToAsn1Object().GetDerEncoded();
```

...but get the same output in STDOUT:

```
Public Comparison: True
Private Comparison: False


Generated Symmetric Key: e2223f1d5132de0c42e77b812bb66d711611e9c8cd87c7aa4f37f2935e825523
Retrieved Symmetric Key: ec77b376c9962f64a5ea194218a39ed7ea491d7c40439e9257fcd23217dcd758
Secrets Equal ---> False
```

## Issue

In other words, using the parsed out `KyberPrivateKeyParameters` from the initial keypair generation: `var keyPair = kpGen.GenerateKeyPair();` works, but this is of course expected yet using the reconstructed private parameters does not.

I believe there is something wrong with the way I am serializing and deserializing the `privateParams` to reconstruct the private key again, but I could not rationalize why it would work for the public but not the private.

I've tried to see some examples of how others have done this online, including the tests from the library itself but I couldn't see any significant difference in my implementation. Correspondingly, here are a few of the resources I've already referenced:
- [x] Showcase of how to test Kyber implementation by [StrathWeb](https://github.com/filipw/Strathweb.Samples.CSharp.Crystals/blob/main/src/Demo/Program.cs)
- [x] The [Kyber test file](https://github.com/bcgit/bc-csharp/blob/master/crypto/test/src/pqc/crypto/test/CrystalsKyberTest.cs) from this library
- [x] An [RSA implementation](https://www.rahulsingla.com/blog/2011/04/serializingdeserializing-rsa-publicprivate-keys-generated-using-bouncy-castle-library/) of what I am trying to do (granted it is old, but the code is similar)

I would really appreciate it if someone can point out something obvious that I may be missing, or point me in the right direction (for example, do I have to create a PEM file and read from that instead for the private key?). 

Given my cryptographic naivete, I am considering this being a problem with the library as a long-shot.

Thank you for reading in advance.

**Comment by kxrna** [comment]
### A small update

A similar implementation from above but with `Saber` seems to work just fine, even with serialized -> deserialized private parameters:

```csharp
  public static void SaberExample()
  {
      var random = new SecureRandom();

      // generate key pair
      var saberGenParams = new SaberKeyGenerationParameters(random, SaberParameters.firesaberkem256r3);
      var saberGen = new SaberKeyPairGenerator();
      saberGen.Init(saberGenParams);
      var keyPair = saberGen.GenerateKeyPair();

      // parse out public and private
      var privateParams = (SaberPrivateKeyParameters)keyPair.Private;
      var publicParams = (SaberPublicKeyParameters)keyPair.Public;

      // faux deserialization
      var privPkcs8 = PqcPrivateKeyInfoFactory.CreatePrivateKeyInfo(privateParams).ToAsn1Object().GetDerEncoded();
      var pubPkcs8 = PqcSubjectPublicKeyInfoFactory.CreateSubjectPublicKeyInfo(publicParams).ToAsn1Object().GetDerEncoded();

      var privPkcs8InB64 = Convert.ToBase64String(privPkcs8);
      var pubPkcs8InB64 = Convert.ToBase64String(pubPkcs8);

      var privateParams2 = (SaberPrivateKeyParameters)PqcPrivateKeyFactory.CreateKey(Convert.FromBase64String(privPkcs8InB64));
      var publicParams2 = (SaberPublicKeyParameters)PqcPublicKeyFactory.CreateKey(Convert.FromBase64String(pubPkcs8InB64));

      Console.WriteLine($"Public Comparison: {Arrays.AreEqual(publicParams.GetEncoded(), publicParams2.GetEncoded())}");
      Console.WriteLine($"Private Comparison: {Arrays.AreEqual(privateParams.GetEncoded(), privateParams2.GetEncoded())}");

      // generate shared secret and encapsulated cipher text
      var kemGenerator = new SaberKemGenerator(random);
      var secretWithEncapsulation = kemGenerator.GenerateEncapsulated(publicParams2);
      var rawSecret = secretWithEncapsulation.GetSecret();
      var cipherText = secretWithEncapsulation.GetEncapsulation();

      // make extractor with private params and get secret
      var kemExtractor = new SaberKemExtractor(privateParams2);
      var extractedSecret = kemExtractor.ExtractSecret(cipherText);

      Console.WriteLine($"\n\nGenerated Symmetric Key: {Hex.ToHexString(rawSecret)}\nRetrieved Symmetric Key: {Hex.ToHexString(extractedSecret)}");

      var secretsEqual = Arrays.AreEqual(rawSecret, extractedSecret);
      Console.WriteLine($"Secrets Equal ---> {secretsEqual}");
  }
```

**Comment by kxrna** [comment]
## A good update

Seems like the issue is actually already fixed, but is not updated in the NuGet release at time of writing. I cloned the repo locally and built it, and then referenced the local `.dll` in my `.csproj` file, and it ended up working as expected.

FYI - I cloned it from `master` at commit [9f36987](https://github.com/bcgit/bc-csharp/commit/9f36987f992075b2f61214f6d83433efd597e93e)

**Comment by peterdettman** [comment]
Sorry you lost some time investigating this, but thanks for confirming the recent updates are now working for you.
