### ISSUE TITLE
Assembly missing version information

### ISSUE THREAD

**Issue by queequac** [bcgit/bc-csharp#483]
While previous versions on nuget carried a `[assembly: AssemblyVersion("1.9.21290")]` and similar, this information is no longer present in AssemblyInfo.cs

While not a big deal in general from a functional point of view, this results in version 0.0.0.0 being shown in the details for the assembly, and the actual version number can no longer be resolved programmatically.

For legal reasons I am listing all open source software with their licenses and version numbers; the latter is automatically retrieved from the assemblies. Unfortunately this does no longer work now, and I am not a fan of hardcoding version infos of dependencies. :)

Could the version be added again? If the removal has technical reasons, maybe as part of the build process?

**Comment by cristianst85** [comment]
Instead you could (and probably should because it's more precise as it includes the Git hash commit) use the `Product version`.

**Comment by peterdettman** [comment]
Our build process uses Nerdbank.GitVersioning, which generates the AssemblyInfo attributes at build time.

You can inspect the DLLs here: https://nuget.info/packages/BouncyCastle.Cryptography/2.2.1.

You can see the version is set to 2.0.0.0; this is for assembly binding compatibility with .NET Framework.

AssemblyFileVersion for the current version is 2.2.1.47552 and is IMO a better choice for your purposes.

**Comment by queequac** [comment]
Found the problem... got tricked with BouncyCastle.NetCore nuget package, which is lacking the version info. :/
