### ISSUE TITLE
Kyber KEM - Differnet Shared Secret on Decapulation

### ISSUE THREAD

**Issue by aicukltd** [bcgit/bc-csharp#492]
Hello!

I’ve written an implementation for Kyber that allows for a private key to be provided to a method and for that private key to create the KemExtractor, except it doesn’t work. 

My key is always different on the decrypt side. 

I've copied the code below, now excuse some of the formatting and methods, I will be refactoring and not prefixing the encapsulation key to the data chunk in production I just am at the point of testing and then I will refactor. I was injecting a new SymmetricCryptographyProvider in the constructor, but again for development, I have just forced it to use my BC impl.

`
public class KyberAsymmetricCryptographyProvider : BaseAsymmetricCryptographyProvider<KyberKeyPairGenerator>
{
    private readonly ISymmetricCryptographyProvider symmetricCryptographyProvider;

    public KyberAsymmetricCryptographyProvider()
    {
        this.symmetricCryptographyProvider = new AesBouncyCastleSymmetricCryptographyProvider();
    }

    public override (byte[] privateKeyParameters, byte[] publicKeyParameters) GenerateKeyPair()
    {
        var kyberKeyPairGenerator = this.InitialiseAlgorithm();

        var keyPair = kyberKeyPairGenerator.GenerateKeyPair();

        var privateKey = keyPair.Private;
        var publicKey = keyPair.Public;

        var kyberPrivateKeyInfo = PqcPrivateKeyInfoFactory.CreatePrivateKeyInfo(privateKey);
        var kyberPublicKeyInfo = PqcSubjectPublicKeyInfoFactory.CreateSubjectPublicKeyInfo(publicKey);

        return
        (
            kyberPrivateKeyInfo.GetEncoded(),
            kyberPublicKeyInfo.GetEncoded()
        );
    }

    public override byte[] Encrypt(byte[] data, byte[] publicKey)
    {
        var kyberPublicKey = (KyberPublicKeyParameters)PqcPublicKeyFactory.CreateKey(publicKey);

        var kemGenerator = new KyberKemGenerator(new SecureRandom());

        var encapsulatedSecret = kemGenerator.GenerateEncapsulated(kyberPublicKey);

        var key = encapsulatedSecret.GetSecret();
        var encapsulatedKey = encapsulatedSecret.GetEncapsulation();

        var encryptedData = this.symmetricCryptographyProvider.Encrypt(data, key, key.GetSubSetOfBytes(16,0));

        return encapsulatedKey.PrependByteArray(encryptedData);
    }

    public override byte[] Decrypt(byte[] data, byte[] privateKey)
    {
        var kyberPrivateKey = (KyberPrivateKeyParameters)PqcPrivateKeyFactory.CreateKey(privateKey);

        var kemExtractor = new KyberKemExtractor(kyberPrivateKey);

        var encapsulatedKey = data.GetSubSetOfBytes(kemExtractor.EncapsulationLength, 0);

        var encryptedData = data.GetSubSetOfBytes(data.Length - kemExtractor.EncapsulationLength, kemExtractor.EncapsulationLength);

        var key = kemExtractor.ExtractSecret(encapsulatedKey); //the key that is extract is different to the key that is used in the Encrypt method.

        return this.symmetricCryptographyProvider.Decrypt(encryptedData, key, key.GetSubSetOfBytes(16, 0));
    }

    protected override KyberKeyPairGenerator InitialiseAlgorithm()
    {
        var kyberKeyPairGenerator = new KyberKeyPairGenerator();

        var kyberKeyGenerationParameters = new KyberKeyGenerationParameters(
            new SecureRandom(),
            KyberParameters.kyber1024_aes
        );

        kyberKeyPairGenerator.Init(kyberKeyGenerationParameters);

        return kyberKeyPairGenerator;
    }
}
`

Any ideas?

**Comment by dghgit** [comment]
Doesn't encapsulatedKey.PrependByteArray(encryptedData) put the encryptedData first?

**Comment by cipherboy** [comment]
@dghgit is correct; in this line in `Encrypt`:

> ```c#
> return encapsulatedKey.PrependByteArray(encryptedData);
> ```

the order is (encrypted, encapsulation); whereas in `Decrypt`:

> ```c#
> var encapsulatedKey = data.GetSubSetOfBytes(kemExtractor.EncapsulationLength, 0);
> var encryptedData = data.GetSubSetOfBytes(data.Length - kemExtractor.EncapsulationLength, kemExtractor.EncapsulationLength);
> ```

the order is (encapsulation, encrypted).

In general, I'd prefer the latter to the former.
