### ISSUE TITLE
Probably bad encoding DerTaggedObject

### ISSUE THREAD

**Issue by harrison314** [bcgit/bc-csharp#503]
While creating a context specific `DerUtf8String` I ran into a problem that other programs could not read it (ASN1 Editor).

Code for replication (BouncyCastle.Cryptography v. 2.2.1):
```cs
DerUtf8String derUtf8String = new DerUtf8String("Hello world!");
Asn1TaggedObject taggedObject = new DerTaggedObject(false, 0, derUtf8String);

byte[] encoded = taggedObject .GetEncoded();

Asn1TaggedObject decodedObject = (Asn1TaggedObject)Asn1Object.FromByteArray(encoded);
Asn1Object innerObject = decodedObject.GetObject();

Console.WriteLine("{0}", innerObject.GetType().Name); // Output is DerOctetString
```
Even BouncyCastle itself does not read the encoded value as `DerUtf8String` string but as `DerOctetString`.

**Comment by peterdettman** [comment]
You've used an implicit tag, which replaces the original Utf8String tag, so the encoding can't be decoded correctly unless the parser is supplied with the missing information, e.g.:

```
DerUtf8String innerObject = (DerUtf8String)decodedObject.GetBaseUniversal(declaredExplicit: false, AsnTags.Utf8String);
```

The `DerOctetString` is just a placeholder the `Asn1TaggedObject` stores until the implicit tag information is supplied. In the general case, the decoding of ASN.1 encodings has to be guided by the relevant ASN.1 types.

**Comment by peterdettman** [comment]
Actually you should be careful to validate the tags when decoding, so it would be better to do:

```
DerUtf8String innerObject = (DerUtf8String)Asn1Utilities.GetContextBaseUniversal(decodedObject, tagNo: 0,
    declaredExplicit: false, AsnTags.Utf8String);
```
