### ISSUE TITLE
Support for ParamSets: TS26-B, TS26-C, TS26-D for GOST34.10-2012-256

### ISSUE THREAD

**Issue by MyznikovAP** [bcgit/bc-csharp#513]
Is there support for these options and will it be added if these options are not currently available?
Support for ParamSets:
TС26-B (1.2.643.7.1.2.1.1.2),
TС26-C (1.2.643.7.1.2.1.1.3),
TС26-D (1.2.643.7.1.2.1.1.4)
for GOST34.10-2012-256 (1.2 .643.7.1)

**Comment by peterdettman** [comment]
Thanks for bringing this to our attention; we didn't have those OIDs. I've now added them (a 2.3.0 release is coming soon).

Note that these are just aliases for the parameter sets from the 2001 standard (1.2.643.2.2.35.1, 1.2.643.2.2.35.2, 1.2.643.2.2.35.3), so we already have the underlying elliptic curves.

**Comment by peterdettman** [comment]
Added in 2.3.0.
