### ISSUE TITLE
Convert Ed25519PrivateKeyParameters to X25519PrivateKeyParameters

### ISSUE THREAD

**Issue by nd1012** [bcgit/bc-csharp#514]
I'd like to use Ed25519 parameters for signature and key exchange (X25519). For this I'd need to convert `Ed25519PrivateKeyParameters` to `X25519PrivateKeyParameters` - is this somehow possible? If yes, how can it be done?

**Comment by Richiedevop** [comment]
Ed25519PrivateKeyParameters

**Comment by Richiedevop** [comment]
X25519PrivateKeyParameters
