### ISSUE TITLE
DTLS fragmentation error?

### ISSUE THREAD

**Issue by ds600** [bcgit/bc-csharp#515]
I am currently trying to setup a .NET CoAP DTLS Server. My problem is that bouncy castles DTLS management kept crashing just giving me an "internal error (80)". So I downloaded the library and debugged through it, finally finding where it throws.
Org.BouncyCastle.Tls.DtlsRecordLayer has the receive method for the package:

```
internal int Receive(Span<byte> buffer, int waitMillis, DtlsRecordCallback recordCallback)
        {
            long currentTimeMillis = DateTimeUtilities.CurrentUnixMs();

            Timeout timeout = Timeout.ForWaitMillis(waitMillis, currentTimeMillis);
            byte[] record = null;

            while (waitMillis >= 0)
            {
                ... // wait millis timeout checks

                int receiveLimit = m_transport.GetReceiveLimit();
                if (null == record || record.Length < receiveLimit)
                {
                    record = new byte[receiveLimit];
                }

                int received = ReceiveRecord(record, 0, receiveLimit, waitMillis);

                int processed = ProcessRecord(received, record, buffer, recordCallback);
                if (processed >= 0)
                    return processed;

                currentTimeMillis = DateTimeUtilities.CurrentUnixMs();
                waitMillis = Timeout.GetWaitMillis(timeout, currentTimeMillis);
            }

            return -1;
        }
```
**ProcessRecord** is what actually decrypts the records and writes it into the buffer. Problem is **ReceiveRecord** returns a bigger byte value, than the buffer is actually sized.

This is the method

```
        private int ReceiveRecord(byte[] buf, int off, int len, int waitMillis)
        {
            if (m_recordQueue.Available > 0)
                return ReceivePendingRecord(buf, off, len);

            int received = ReceiveDatagram(buf, off, len, waitMillis);
            if (received >= RecordHeaderLength)
            {
                this.m_inConnection = true;

                ... // Epoch checks, to make sure what to read

                int recordHeaderLength = recordEpoch.RecordHeaderLengthRead;
                if (received >= recordHeaderLength)
                {
                    int fragmentLength = TlsUtilities.ReadUint16(buf, off + recordHeaderLength - 2);
                    int recordLength = recordHeaderLength + fragmentLength;
                    if (received > recordLength)
                    {
                        m_recordQueue.AddData(buf, off + recordLength, received - recordLength);
                        received = recordLength;
                    }
                }
            }

            return received;
        }
```

**EDIT**
I first assumed a fragmentation error, but after closer investigation I realized that the **ReceivePendingRecord** function is only triggered on handshake, not on the application data packages afterwards. So I assume the record that triggers the exception isn't actually split into fragments, leaving me with no idea at all

**Comment by ds600** [comment]
Probably not a problem of bouncy castle, but of another library that I use (CoAP.NET) that handles some of the DTLS session management. I'll close this issue until I can be certain

**Comment by peterdettman** [comment]
We call GetReceiveLimit on the DtlsTransport to size the receive buffer, so it's important to return an appropriate value there. In any case a call to DtlsTransport.Receive should never return a value larger than the available space in the buffer. I've added an extra guard for the latter case.

Note that individual datagrams may contain one or more complete records (no record splitting across datagrams); this usually only happens during the handshake. Individual handshake messages may also be fragmented across multiple records.

**Comment by ds600** [comment]
I just found out that this issue is not happening because of fragmentation, but because the buffer of the previous (smaller) message is used and it tries to push the new message in a wrong buffer. I'll continue my investigation on how this is happening
