### ISSUE TITLE
Release notes for v2.3.0

### ISSUE THREAD

**Issue by CollinAlpert** [bcgit/bc-csharp#518]
Hi, where can I find release notes for v2.3.0? I checked on https://www.bouncycastle.org/csharp/, but the latest release notes are for v2.2.1.

**Comment by peterdettman** [comment]
See https://github.com/bcgit/bc-csharp/blob/cf1829ba51741d96e67644bd574ca062740145e1/crypto/Readme.html#L332-L358 until they are updated on the website.

**Comment by CollinAlpert** [comment]
Thank you!
