### ISSUE TITLE
Release 1.8.1 - NuGet Publish

### ISSUE THREAD

**Issue by HockeyJustin** [bcgit/bc-csharp#52]
Hi,

Sorry - looked on your website but wasn't sure who to contact.

I notice that release 1.8.1 has not been put on Nuget (it's currently v1.7).

Please could you let me know - Have you stopped updating NuGet, or is this in progress?

I could put the current release on NuGet, but thought that would be rude seeing as I haven't written any of the code (and it wouldn't update the existing version).

Kind regards,

Justin

**Comment by bcgit** [comment]
The current release is here:

https://www.nuget.org/packages/BouncyCastle.Crypto.dll/1.8.1

We're still sorting out the chaos on this one.

**Comment by HockeyJustin** [comment]
No problem. Thanks for getting back to me and for the link. 

Kind regards,

Justin
