### ISSUE TITLE
Add support for mixed hashing (RSA/ECB/OAEPWithSHA-256AndMGF1Padding)

### ISSUE THREAD

**Issue by wizche** [bcgit/bc-csharp#53]
In java (up to JDK8) per default the MGF digesting algorithm used is SHA1, currently there is no way to specify a different hashing algorithm between OAEP and MGF.

One (bad way) to circumvent this is to use reflection to change mgfHash field in the cipher:

``` c#
var cipherImpl = GetInstanceField(c.GetType(), c, "cipher");
var newDigest = new Sha1Digest();
var prop = cipherImpl.GetType().GetField("mgf1Hash", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
prop.SetValue(cipherImpl, newDigest);
```

**Comment by fabiogermann** [comment]
maybe this pull request will help: https://github.com/bcgit/bc-csharp/pull/54/files

**Comment by bcgit** [comment]
Just one thing with this one - which Java provider is being talked about here? The BC one, in line with the recommended practice with OAEP, defaults to the same mask generation digest as the base one.

Fabio's patch will obviously help with this, but I am wondering about the usage at the Java end - if possible OAEP should be configured to use the same digest in both roles.

**Comment by wizche** [comment]
I'm talking about the SUN provider, which, when using the default cipher initialisation, doesn't use the same digest algorithm for both OAEP and MGF. You are completely right that changing the configuration on the java side (setting both digest the same) is the best solution. But as you know, sometimes legacy application need much time to perform such a change...

I tested the pull request of Fabio and worked as intended. Maybe you could add a warning when using incongruent digests that suggest the users to be compliant with recommendation at some point.

**Comment by wizche** [comment]
BTW: There is an open issue in OpenJDK targeting this very problem: https://bugs.openjdk.java.net/browse/JDK-7038158

**Comment by fabiogermann** [comment]
Is there anything missing in this issue and related pull request? I know it's an old one but still would be great to have this merged.

**Comment by dghgit** [comment]
So I've just checked and the sun provider is still doing this. I'd say this issue will never be fixed, the other weird thing the cipher implementation is using BER for the parameters encoding... Anyway, I've merged the patch.
