### ISSUE TITLE
TestInvalidNegativeSerialNumberTest15 failed 

### ISSUE THREAD

**Issue by andbene72** [bcgit/bc-csharp#56]
This is the test result

  Expected: True
  But was:  False

   in NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   in NUnit.Framework.Assert.IsTrue(Boolean condition)
   in Org.BouncyCastle.Tests.Nist.NistCertPathTest.DoExceptionTest(String trustAnchor, String[] certs, String[] crls, Int32 index, String mesStart, String mesEnd) in C:\Users\andrea\Documents\GitHub\bc-csharp\crypto\test\src\test\nist\NistCertPathTest.cs:riga 627
   in Org.BouncyCastle.Tests.Nist.NistCertPathTest.TestInvalidNegativeSerialNumberTest15() in C:\Users\andrea\Documents\GitHub\bc-csharp\crypto\test\src\test\nist\NistCertPathTest.cs:riga 184

the error is somewhere in the test I think, not in the library, at line 627 of NistCertCertPathtest.cs, in my italian system e.Message is
"Certificate revocation after gio apr 19 14:57:20 Z 2001, reason: keyCompromise" 
but it's tested startwith against
"Certificate revocation after Thu Apr 19 14:57:20"

Andrea

**Comment by peterdettman** [comment]
Thanks for the report, I've removed the date-time part of the string comparison.
