### ISSUE TITLE
X509SignatureFactory : ISignatureFactory doesn't verify construction with a private key

### ISSUE THREAD

**Issue by kyanha** [bcgit/bc-csharp#58]
X509SignatureFactory doesn't verify that it is constructed with a private key.  An error here will eventually be discovered when it comes time to generate the signature, but because the Pkcs10CertificationRequest constructor verifies that the private key is private (though not that it matches publicKey) I think the constructor of an ISignatureFactory should probably check for its construction with valid parameters before it gets to generation time -- if only to make it quicker for clients to detect the error, and thus quicker to debug the issues they have.

**Comment by peterdettman** [comment]
Checks have been added to the Asn1SignatureFactory constructor, which I assume addresses this.
