### ISSUE TITLE
Constructor for X9FieldElement would need static ECCurve.FromBigInteger method

### ISSUE THREAD

**Issue by kyanha** [bcgit/bc-csharp#59]
```
    public X9FieldElement(
        BigInteger      p,
        Asn1OctetString s)
```

would require a static ECCurve.FromBigInteger method in order to comply with the [Obsolete] attribute  on the FpFieldElement(BigInteger, BigInteger) constructor.  I understand that it was probably marked obsolete because its use is almost always going to cause more processing than originally intended due to FpFieldElement(BigInteger, BigInteger) performing additional residue calculation.  However... there would also be an additional processing window to figure out if p was a known curve so its class could be appropriately invoked or instantiated.

I don't know if it's appropriate for FpFieldElement(BigInteger, BigInteger) to be marked obsolete, given that this X9FieldElement constructor is not obsolete.

In any case, I think a #pragma warning disable CS0618 around the offending X9FieldElement constructor would be appropriate, as it's a utility function to permit passing an arbitrary BigInteger from a Asn1OctetString.

However, I also don't know what your design decisions here actually are, so I can't figure out how best to approach this.

**Comment by kyanha** [comment]
(I should mention that I'm trying to clear out the CS0618 warnings when building crypto.dll.  That's where this raft of bug reports -- 57, 58, and 59 -- are coming from.)

**Comment by kyanha** [comment]
I've currently got this constructor in my local tree as:

    #pragma warning disable CS0618
        [Obsolete("This method will always recalculate the residue of p, which may be undesirable")]
        public X9FieldElement(
            BigInteger		p,
            Asn1OctetString	s)
            : this(new FpFieldElement(p, new BigInteger(1, s.GetOctets())))
        {
        }
    #pragma warning restore CS0618

Is this a valid approach?

**Comment by peterdettman** [comment]
The offending X9FieldElement constructors are now Obsolete themselves.
