### ISSUE TITLE
How to implement RSA512 (SSLeavy)

### ISSUE THREAD

**Issue by priore** [bcgit/bc-csharp#62]
Hello, how can I implement the signature, and verification, for the strandard RSA 512 (SSLeavy) with BouncyCastle ?

**EDIT:**

I have tried to verify a signature, but return always false

```c#
   static public bool VerifyData(string value, string b64_signature, string pemFileName)
    {
        byte[] data_in = Encoding.UTF8.GetBytes(value);
        byte[] hash = Convert.FromBase64String(b64_signature);
        return VerifyData(data_in, hash, pemFileName);
    }

    static public bool VerifyData(byte[] data, byte[] signature, string pemFileName)
    {
            RsaKeyParameters key = ReadPem(pemFileName) as RsaKeyParameters;
            ISigner sig = SignerUtilities.GetSigner("SHA512WITHRSA");
            sig.Init(false, key);
            sig.BlockUpdate(data, 0, data.Length);
            return sig.VerifySignature(signature);
    }

    static private Object ReadPem(string fileName)
    {
        string fname = HttpContext.Current.Server.MapPath("/pem/" + fileName);
        using (TextReader stream = File.OpenText(fname))
        {
            PemReader pem = new PemReader(stream);
            return pem.ReadObject();
        }
    }
```

**Comment by peterdettman** [comment]
Github is not the appropriate place for how-to questions. We have mailing lists, and any search engine should turn up many examples of how to sign/verify with RSA using BC.

The code you give for verification looks basically OK, but it's impossible to say why it "doesn't work" for your situation unless we know how the putative signature was created. Given your mention of "RSA 512", I might point out that the 512 in SHA512WITHRSA refers to the SHA512 digest and not 512-bit RSA. I would double-check the actual algorithm used for the signature.
