### ISSUE TITLE
SNK key file

### ISSUE THREAD

**Issue by KimikoMuffin** [bcgit/bc-csharp#70]
So ... is the [BouncyCastle.snk](https://github.com/bcgit/bc-csharp/blob/master/BouncyCastle.snk) file the same one that's being used to generate the release versions? Because if it *is*, then that means that anyone could compile it with the "legitimate" key name, which would [subvert the whole point of strong-named assemblies](https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx).

My recommendation is the following:
1. Delete BouncyCastle.snk permanently.
2. Create an entirely separate snk file; keep it *secret*, keep it *away* from the git repository, *do not release or distribute it __AT ALL__*. In fact, you should probably make one SNK file for each of the different versions (PCL.snk, Android.snk, iOS.snk, etc; c.f. #61).
3. After building each version for release, [sign each separate version with their respective SNK files](https://msdn.microsoft.com/en-us/library/xc31ft41(v=vs.110).aspx) (that link is specific to Visual Studio, but it explains the general principle), and distribute them through an unimpeachable source, i.e. the Releases page.

Yes, this will probably result in compatibility issues, given that people will need to recompile anything that references bc-csharp, but I think this is outweighed by the risk of, say, someone adding malicious code to the source and then passing it off as legitimate.

**Comment by jstedfast** [comment]
strong-named assemblies aren't about security
