### ISSUE TITLE
Performance issue when CRL list is very large

### ISSUE THREAD

**Issue by thuannguy** [bcgit/bc-csharp#72]
Hi,
I have a problem with using BC to validate certificate revocation when the CRL is very large, e.g. 10MB or 20MB. When I look into relevant code of the IsRevoked method below, I find some potential issues. First of all, the c.GetRevokedCertificates() returns a copy of all revoked certificates. Secondly, because it loops through all items sequently and the list is very large, it takes about 200ms to verify a single certificate which is a big hit to my application. While I can easily fork and improve code to eliminate the copy and change to use Dictionary, I would like to know if there are any potential issues with doing that? Or to put it differently, could you please give me some insight about why code was done like that in the first place?

Thank you very much :)

		public virtual bool IsRevoked(
			X509Certificate cert)
		{
			CrlEntry[] certs = c.GetRevokedCertificates();

			if (certs != null)
			{
				//BigInteger serial = ((X509Certificate)cert).SerialNumber;
				BigInteger serial = cert.SerialNumber;

				for (int i = 0; i < certs.Length; i++)
				{
					if (certs[i].UserCertificate.Value.Equals(serial))
					{
						return true;
					}
				}
			}

			return false;
		}

**Comment by peterdettman** [comment]
I don't think there's any specific reason for this, it's just not optimized. Probably it's been used primarily to parse CRLs and contribute them to some sort of database for actual queries (I think typically some sort of LDAP setup in Java world, not sure of options here).
