### ISSUE TITLE
PKCS12Store.GetCertificateChain() fails when signing algorithm is 1.3.14.3.2.29 (legacy SHA1 with RSA)

### ISSUE THREAD

**Issue by MJRichardson** [bcgit/bc-csharp#74]
Microsoft's `makecert.exe` utility by default generates certificate signed using the [1.3.14.3.2.29 - SHA1 with RSA signature algorithm](http://www.alvestrand.no/objectid/1.3.14.3.2.29.html).

This algorithm is currently not recognised by the `SignerUtilities` class, causing the  `PKCS12Store.GetCertificateChain()` method to fail with:

```
Org.BouncyCastle.Security.SecurityUtilityException: Signer 1.3.14.3.2.29 not recognised. 
at Org.BouncyCastle.Security.SignerUtilities.GetSigner(String algorithm) 
```

**Comment by peterdettman** [comment]
Thanks for the report, and sorry for the delay. We've now included this OID (OiwObjectIdentifiers.Sha1WithRsa) in SignerUtilities and a few other places it was also missing, and similarly for a few other OIW OIDs.
