### ISSUE TITLE
Missing Java asn1.DLSet and asn1.DLSequence

### ISSUE THREAD

**Issue by ExperimentsAndIdeas** [bcgit/bc-csharp#77]
I'm about to port some java code that leverages this.  I don't see it in C#, but it's present in Java BC 

https://github.com/bcgit/bc-java/blob/ae63147936376e85e068c7b63373d4e930c3fe58/core/src/main/java/org/bouncycastle/asn1/DLSequence.java

https://github.com/bcgit/bc-java/blob/ae63147936376e85e068c7b63373d4e930c3fe58/core/src/main/java/org/bouncycastle/asn1/DLSet.java

**Comment by peterdettman** [comment]
The BC Java ASN.1 API was revamped a few years ago, but those changes weren't carried over to BC C#, which still uses the older style. So unfortunately, a literal translation will not be possible, but it's usually pretty simple to convert nonetheless.

Is the code you want to port a part of the Java BC distribution?

**Comment by makerofthings7** [comment]
I can port this myself, but just wanted to be ready for conflicts in case I get them.

**Comment by makerofthings7** [comment]
When I inherit from  :` Org.BouncyCastle.Asn1.Asn1Sequence, IEnumerable` the compiler acts really strange.  It says that I'm not implementing the member/method, but I am.  I even let intellisense create it for me.

Is there something special/unusual about the base class to confuse VS2017?

 CS0534	'DLSequence' does not implement inherited abstract member 'Asn1Object.Encode(DerOutputStream)'	

 CS0115	'DLSequence.Encode(DerOutputStream)': no suitable method found to override

**Comment by makerofthings7** [comment]
Also it does seem like this class is implemented in the Java BC distro

https://github.com/bcgit/bc-java/blob/ae63147936376e85e068c7b63373d4e930c3fe58/core/src/main/java/org/bouncycastle/asn1/DLSequence.java

**Comment by jstedfast** [comment]
Can I see your code? Maybe I can help.

**Comment by jstedfast** [comment]
Make sure your override is marked `internal`

**Comment by peterdettman** [comment]
To be clear, I would guess porting the ASN.1 classes (DLSequence etc.) is not the way to go. By "usually pretty simple to convert" I meant to convert the java code you're actually porting (that uses the ASN.1 API) to use the existing C# API instead.
