### ISSUE TITLE
Contant Time Comparisons are *not* Always Constant

### ISSUE THREAD

**Issue by StrangeWill** [bcgit/bc-csharp#80]
https://github.com/bcgit/bc-csharp/blob/1cdf80bc3f540b5531c158dacf4d67976b028fef/crypto/src/util/Arrays.cs#L76

We bail early if the lengths don't match, and will bail *way* early, which leaks information about the length of the byte array.

**Comment by cipherboy** [comment]
@StrangeWill In general, unless there's a fixed upper limit to compare against, you're going to at least leak the timing information one of the two buffers. This leaks the timing information on the shorter of the two. Most other implementations (e.g., [Go's](https://pkg.go.dev/crypto/subtle#ConstantTimeCompare) which bails early like ours does, the [JDK's](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/security/MessageDigest.java#L473-L496) which bases on the first passed array (which you'll know is shorter if you passed the second array and it is longer -- or can tell the size of the second array if you control the first array), or [OpenSSL](https://github.com/openssl/openssl/blob/1751185154ab1f1a796e0f39567fe51c8e24b78d/crypto/cmp/cmp_vfy.c#L87-L91) which pairs short-circuiting length comparisons with the constant time comparison over two equal-length arrays). 

If your implementation depends on not knowing the size of either of the two arrays, I'd suggest copying them into a length-prefixed, zero-padded byte array and then perform the constant time comparison over the two.
