### ISSUE TITLE
crypto.dotnet, crypto.pcl, and crypto.pcl2 do not compile

### ISSUE THREAD

**Issue by KimikoMuffin** [bcgit/bc-csharp#82]
The PCL versions do not compile. The culprit is [KCcmBlockCipher.cs](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/modes/KCcmBlockCipher.cs#L257) -- in PCL, MemoryStreams apparently don't have a GetBuffer() method.

**Comment by peterdettman** [comment]
Thanks, I'll take a look.

**Comment by peterdettman** [comment]
Fixed in our git. Once the GitHub mirror updates (a day or two) please confirm that it works for you.

**Comment by KimikoMuffin** [comment]
The projects themselves compile now, but now crypto.tests.Net45 doesn't; [DHTest.cs](https://github.com/bcgit/bc-csharp/blob/master/crypto/test/src/test/DHTest.cs#L711), [SecP256R1FieldTest.cs](https://github.com/bcgit/bc-csharp/blob/master/crypto/test/src/math/ec/custom/sec/test/SecP256R1FieldTest.cs#L153), and [SecP384R1FieldTest.cs](https://github.com/bcgit/bc-csharp/blob/master/crypto/test/src/math/ec/custom/sec/test/SecP384R1FieldTest.cs#L137) complain that `Platform`, `Nat256`, and `Nat` respectively are inaccessible due to their protection level.

**Comment by onovotny** [comment]
You should not need this.... Use the `netstandard` version in my PR or from https://github.com/onovotny/bc-csharp. That has the current portable code, which builds for `netstandard1.0`, `netstandard1.3`, `net4` and the legacy `portable-net4+sl5+wp8+win8+wpa81` TFM.

**Comment by peterdettman** [comment]
All those test references appear to have been removed already, so closing.
