### ISSUE TITLE
DigestName should be EncryptionName?

### ISSUE THREAD

**Issue by ljiranek** [bcgit/bc-csharp#83]
In Cms.SignerInformation.cs line 348 DigestName is used to constuct the signature name. This should be the EncryptionName when the HASH algorithm is defined by EncryptionOid. 

The fix was also done in Java BouncyCastle 2 years ago (9.5.2015) in DefaultCMSSignatureAlgorithmNameGenerator.java method getSignatureName

The source data (testing SOD) can be found in original issue created in Jira: http://www.bouncycastle.org/jira/browse/BMA-134

**Comment by dghgit** [comment]
Thanks for the reminder, this is now fixed. The code will now try the enc OID first and then fall back to the digest oid.
