### ISSUE TITLE
Where can I find the PGPDigestCalculator and the PBESecretKeyEncryptor?

### ISSUE THREAD

**Issue by RobOrville** [bcgit/bc-csharp#84]
Hey guys, 

I want to develop a PGPKeyGenerator and have an example from the java implementation. My problem is that I can´t find the following Types:

- PGPDigestCalculator
- PBESecretKeyEncryptor

Can you say me where I can find these types in the C# implementation?

Best regards,
Rob 

_Sent from my Samsung SM-A320FL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bcgit** [comment]
The C# API is slightly different - you'll find the classes for what you want in the Org.BouncyCastle.Bcpg.OpenPgp in the C# distribution

**Comment by RobOrville** [comment]
Thanks for your answer! 
But I dont find the the classes, maybe you can help me I want to programm the following lines of code:
`PGPDigestCalculator sha1Calc =
            new BcPGPDigestCalculatorProvider()
            .get(HashAlgorithmTags.SHA1);`
 ` PGPDigestCalculator sha256Calc =
            new BcPGPDigestCalculatorProvider()
            .get(HashAlgorithmTags.SHA256);`
`PBESecretKeyEncryptor pske =
            (new BcPBESecretKeyEncryptorBuilder
             (PGPEncryptedData.AES_256, sha256Calc, s2kcount))
            .build(pass);`

Thank you again and have a nice day!
Best regards,
Rob
