### ISSUE TITLE
Question: how to determine the dwkeysize from a PEM file

### ISSUE THREAD

**Issue by shhsu** [bcgit/bc-csharp#90]
Hi

This might be a silly question, but I am not quite well versed in crypto and I am hoping to get some answers here.

I have a private key PEM file. When I call 
```
openssl rsa -text -in example.pem
```
I got back this in the first line in output
```
Private-Key: (2048 bit)
```

I use the DotNetCore version of bouncy castle to implement a method to create a C# RSA signing credential. The method look something like this:

```csharp
....
using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.OpenSsl;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
....
        public static SigningCredentials GetSigningCredentials(this string pemString, JwtPayload payload)
        {
            var keySize = 2048; // made a wild guess
            var pr = new PemReader(new StringReader(pemString));
            var keyPair = (AsymmetricCipherKeyPair)pr.ReadObject();
            var privateKey = (RsaPrivateCrtKeyParameters)keyPair.Private;
            var rsaParam = privateKey.ToRSAParameters(keySize); // my implementation that pads the bytes to predefined length
            var provider = new RSACryptoServiceProvider(keySize); // key size is passed in here!
            provider.ImportParameters(rsaParam);
            var key = new RsaSecurityKey(provider);
            return new SigningCredentials(key, "RS256");
        }
```

My question is, is there an API in bouncy castle to determine the keySize so I don't have to make a guess here in the first line of my method?

thank you

**Comment by shhsu** [comment]
I have noticed that I did not have to pass in the `keySize` in the constructor as it can use the default key. However my ToRSAParameters does need to know the actual key size so I can pad each parameter to the right length (sometimes the bigInteger objects are a little too small and the returned `byte[]` was shorter than `RSACryptoServiceProvider.ImportParameters` required

**Comment by bcgit** [comment]
For RSA the key size is the bitLength of the modulus.

**Comment by shhsu** [comment]
Got it. Thank you
