### ISSUE TITLE
KeyParameter.cs - Integer Overflow

### ISSUE THREAD

**Issue by dganesa** [bcgit/bc-csharp#91]
Hi,
This integer overflow in KeyParameter.cs may not be a security vulnerability.

It is possible to create a memory exception by setting the keyLen to say INT_MAX and keyOff to 1 and set the byte[] key to a small array of length 2, for example.

This vulnerability will then create a byte array of len INT_MAX, which often crashes.

`public KeyParameter(
            byte[]	key,
            int		keyOff,
            int		keyLen)
        {
			if (key == null)
				throw new ArgumentNullException("key");
			if (keyOff < 0 || keyOff > key.Length)
				throw new ArgumentOutOfRangeException("keyOff");
			if (keyLen < 0 || (keyOff + keyLen) > key.Length)
				throw new ArgumentOutOfRangeException("keyLen");

			this.key = new byte[keyLen];
            Array.Copy(key, keyOff, this.key, 0, keyLen);
        }
`

**Comment by peterdettman** [comment]
Thanks, I've now changed the 'keyLen' check to:
`            if (keyLen < 0 || keyLen > (key.Length - keyOff))`
