### ISSUE TITLE
Pkcs10CertificationRequestDelaySigned ctor throws when constructed from encoded bytes of another instance

### ISSUE THREAD

**Issue by DmitriNymi** [bcgit/bc-csharp#93]
When trying to create new instance of Pkcs10CertificationRequestDelaySigned from encoded bytes of another instance, throws System.ArgumentException: illegal object in GetInstance: Org.BouncyCastle.Asn1.DerNull
    at Org.BouncyCastle.Asn1.DerBitString.GetInstance(Object obj)
   at Org.BouncyCastle.Asn1.Pkcs.CertificationRequest..ctor(Asn1Sequence seq)

How to reproduce in C# :

const string csrEncoded = @"here goes the base64 encoded string for CSR";
var originalCsr = new Pkcs10CertificationRequest( Convert.FromBase64String(csr));

CertificationRequestInfo cri = originalCsr.GetCertificationRequestInfo();

Asn1Set attributes = cri.Attributes ?? new DerSet();
// removed code that changes attributes
var attributesSet = attributes ;

SubjectPublicKeyInfo subjectPki = cri.SubjectPublicKeyInfo;
            
AsymmetricKeyParameter publicKey = PublicKeyFactory.CreateKey(subjectPki);

string signatureAlgorithm = originalCsr.SignatureAlgorithm.Algorithm.Id;
            
 // build new CSR from original + added attributes
var csrWithPassword = new Pkcs10CertificationRequestDelaySigned(signatureAlgorithm, cri.Subject, publicKey, attributesSet);

var csrWithPasswordBytes = csrWithPassword.GetDerEncoded();

// Here we get exception while using the der-encoded bytes of another instance,
// because CertificationRequest.sigBits cannot parse NULL 
var csr2 = new Pkcs10CertificationRequestDelaySigned(csrWithPasswordBytes );

**Comment by DmitriNymi** [comment]
Answering my own question, you can call:

csrWithPassword.SignRequest(new byte[]{});
before extracting DER encoded bytes, thus pretending to have some default signature

Still this solution looks like patch.

**Comment by DmitriNymi** [comment]
Continuing with delay signing I managed to sign CSR's hash with RSA but not with ECDSA. Signature validation fails when inserting signature of hash into CSR. I posted this question online: 
https://stackoverflow.com/questions/46182659/how-to-delay-sign-the-certificate-request-using-bouncy-castle-pkcs10certificatio

**Comment by sefai** [comment]
Hello @DmitriNymi 

Does this line _"csrWithPassword.SignRequest(new byte[]{});"_ has any side effects on the resulting certificate?

Regards,

**Comment by DmitriNymi** [comment]
Hello sefai,
This line "csrWithPassword.SignRequest(new byte[]{});" is there to enable extracting CSR in DER format after password is inserted. This is later used to calculate hash that is signed but the other party, and that signature will be added to the final CSR. 
So that the previous signature doesn't play any role since it is overwritten in the last step.
Also it is very strange that exactly the same code works for RSA but not ECDSA.

**Comment by DmitriNymi** [comment]
I found the problem with the way I was calculating the signature. For some reason it doesn't work for ECDSA, so here is the solution that works both for ECDSA and RSA (with SHA-256 hash). 
In short when calculating signature use "NONEwithECDSA" or "NONEwithRSA" and also RSA requires adding DigestInfo instead of bair signature as in ECDSA (I am still wondering why ?) .

`
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Org.BouncyCastle.Asn1;
using Org.BouncyCastle.Asn1.Sec;
using Org.BouncyCastle.Asn1.X509;
using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Crypto.Operators;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.Math;
using Org.BouncyCastle.Pkcs;
using Org.BouncyCastle.Security;

namespace Test {

[TestClass]
public class DelaySigningTest
{
 const string hashAlgorithm = "SHA256";

[TestMethod]
 public void TestDelaySigning()
 {
            const string hashAlgorithm = "SHA256";
            const string signAlgorithm = "ECDSA"; // or "RSA" 
            bool isRsa =false; // or true for RSA

           var keys = new Keys(signAlgorithm);

           // Create CSR
            var signatureAlgorithm = hashAlgorithm + "with" + signAlgorithm; // "SHA256withECDSA" or "SHA256withRSA"
            byte[] octetData = CreateCsr(keys.SignKeyPair, signatureAlgorithm);
            byte[] csrWithPass = AppendPassword(octetData, "some-password");

            byte[] hash = BuildHash(csrWithPass, hashAlgorithm);

            // Sign the hash
            string singingAlgorithm2 = "NONEwith" + signAlgorithm;
            byte[] signature = Sign(hash, singingAlgorithm2, hashAlgorithm, keys.SignKeyPair.Private, isRsa );

            byte[] csrSigned = AppendSignature(csrWithPass, signature);

            Verify(csrSigned);
 }

        public byte[] BuildHash(byte[] csr, string algorithm)
        {
            var originalCsr = new Pkcs10CertificationRequestDelaySigned(csr);
            byte[] dataToSign = originalCsr.GetDataToSign();
            byte[] digest = DigestUtilities.CalculateDigest(algorithm, dataToSign);
            return digest;
        }

        public static byte[] Sign(byte[] hash, string signerAlgorithm, string hashAlgorithm, 
                                                     AsymmetricKeyParameter privateSigningKey, bool isRsa)
        {
            if (isRsa)
            {
                var hashAlgorithmOid = DigestUtilities.GetObjectIdentifier(hashAlgorithm).Id;

                var digestAlgorithm = new AlgorithmIdentifier(new DerObjectIdentifier(hashAlgorithmOid), 
                          DerNull.Instance);

                var dInfo = new DigestInfo(digestAlgorithm, hash);
                byte[] digest = dInfo.GetDerEncoded();
                hash = digest;
            }
            
        private void Verify(byte[] csrSigned)
        {
            Assert.IsNotNull(csrSigned);

            var csr = new Pkcs10CertificationRequest(csrSigned);

            bool isValid = csr.Verify();

            Assert.IsTrue(isValid, "Signature verification failed for CSR.");
          }

        private byte[] CreateCsr(AsymmetricCipherKeyPair signingKeyPair, string signatureAlgorithm)
        {
            var key = signingKeyPair;

            Dictionary<DerObjectIdentifier, string> values = CreateSubjectValues("my common name");

            var subject = new X509Name(values.Keys.Reverse().ToList(), values);

            DerSet attributes = null;
            
            var pkcs10Csr = new Pkcs10CertificationRequestDelaySigned(
                signatureAlgorithm,
                subject,
                key.Public,
                attributes,
                key.Private);

            byte[] derEncoded = pkcs10Csr.GetDerEncoded();
            return derEncoded;
        }
}

    /// <summary>
    /// Helper that stores key-pair as required
    /// </summary>
    class Keys
    {
        private static readonly SecureRandom Rand;

        private readonly string _keyAlgorithm;

        private readonly KeyGenerationParameters _keyGenerationParameters;

        private readonly IAsymmetricCipherKeyPairGenerator _keyPairGenerator;

        private AsymmetricCipherKeyPair _signKeyPair;
        public AsymmetricCipherKeyPair SignKeyPair => _signKeyPair ?? (_signKeyPair = MakeKeyPair());

        static Keys()
        {
            Rand = new SecureRandom();
        }

        public Keys(string keyAlgorithm)
        {
            _keyAlgorithm = keyAlgorithm;
            _keyGenerationParameters = CreateKeyGenerationParameters();
            _keyPairGenerator = CreateKeyPairGenerator();
        }

        private KeyGenerationParameters CreateKeyGenerationParameters()
        {
            SecureRandom random = Rand;
            //SecureRandom random = SecureRandom.GetInstance("SHA256PRNG");

            if (_keyAlgorithm == "RSA")
            {
                return new RsaKeyGenerationParameters(BigInteger.ValueOf(65537), random, 2048, 25);
            }

            if (_keyAlgorithm == "ECDSA")
            {
                return new ECKeyGenerationParameters(SecObjectIdentifiers.SecP256r1, random);
            }

            throw new NotSupportedException(_keyAlgorithm);
        }

        private IAsymmetricCipherKeyPairGenerator CreateKeyPairGenerator()
        {
            var keyPairGenerator = GeneratorUtilities.GetKeyPairGenerator(_keyAlgorithm);
            keyPairGenerator.Init(_keyGenerationParameters);

            return keyPairGenerator;
        }

        public AsymmetricCipherKeyPair MakeKeyPair()
        {
            return _keyPairGenerator.GenerateKeyPair();
        }
    }    
}
`

**Comment by dghgit** [comment]
Closing as resolved.
