### ISSUE TITLE
Pkcs12Store with unmarked keys

### ISSUE THREAD

**Issue by jperlope** [bcgit/bc-csharp#94]
I am using BouncyCastle to import private Keys pkcs12 and decrypt data. I am using a code like this:
```javascript
            Pkcs12Store pkcs12Store = new Pkcs12Store(new MemoryStream(privateKey, false), password.ToCharArray());

            var cipher = CipherUtilities.GetCipher("RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING");
            var input = HexToByteArray(encriptedData);

            ICipherParameters cipherParameters = pkcs12Store.GetKey("unmarked").Key;//**

            cipher.Init(false, cipherParameters);
            var output = cipher.DoFinal(input, 0, input.Length);
            var outputText = Encoding.ASCII.GetString(output);
            return outputText
```

I've checked that the alias is "unmarked" using Version 1.7X when I import my private keys. But in version 1.8.1, with the same data input, there is not alias because Pkcs12Store.keys is empty (at line **).
I temporarily fix it, with this code at the end of method Load in class Pkcs12Store:

```javascript
     if (keys.Keys.Count == 0 && unmarkedKeyEntry != null)
     {
                keys["unmarked"] = unmarkedKeyEntry;
     }
```

Please, could you check this case?

**Comment by peterdettman** [comment]
Finally found and fixed this regression, it will be in 1.8.4.
