### ISSUE TITLE
Which is the most recommended NuGet library for .NET Core 2.0?

### ISSUE THREAD

**Issue by nopara73** [bcgit/bc-csharp#96]
https://www.nuget.org/packages?q=bouncycastle

**Comment by jstedfast** [comment]
You want this package: https://www.nuget.org/packages/Portable.BouncyCastle/

**Comment by nopara73** [comment]
Indeed, that package is referenced heavily in the issues here. I close this issue. If anyone has more to add to the discussion, I reopen it.
