### ISSUE TITLE
when can support .net standard???

### ISSUE THREAD

**Issue by Varorbc** [bcgit/bc-csharp#97]
when can support .net standard???

**Comment by jstedfast** [comment]
You can use https://www.nuget.org/packages/Portable.BouncyCastle/ if you need .net standard support.

**Comment by ViktorHofer** [comment]
Does that mean that this package is obsolete? https://www.nuget.org/packages/BouncyCastle/

**Comment by harleyknd1** [comment]
No, the above nuget package provides a portable implementation which doesn't include everything from bouncy castle and is oriented towards performance

**Comment by onovotny** [comment]
@harleyknd1 Not sure what you're referring to. `Portable.BouncyCastle` does provide everything in BC (the .NET Standard 2.0 version has full coverage). The `BouncyCastle` is the official library and will eventually contain the changes from the portable version once they merge the PR.
